import type { Preset } from "../types.js";

export const design: Preset[] = [
  {
    id: "app-icon",
    category: "design",
    title: "App icon",
    description: "Polished rounded-square app icon with depth. iOS/Android/store-ready look.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "modern app icon designed on a rounded-square (squircle) tile, built like a contemporary iOS/Android home-screen icon",
      composition: "one bold centered glyph sitting on a clear optical grid, generous even padding so the silhouette reads instantly and stays legible scaled down to 48px",
      setting: "smooth filled tile, either flat color or one restrained diagonal gradient — never a busy scene",
      lighting: "soft top-down key light with a short grounded contact shadow, giving subtle clay-like depth without heavy skeuomorphism",
      color: "tight two- or three-color system with one confident accent, strong figure-ground contrast between glyph and tile",
      mood: "clean, premium, instantly recognizable, brand-ready",
      detail: "crisp geometric construction, consistent corner radii, smooth anti-aliased edges, a single memorable mark that survives at small sizes",
    },
    avoid: ["fine intricate detail", "text or lettering", "photorealism", "cluttered or layered symbolism", "harsh drop shadows", "muddy low contrast", "watermark"],
  },
  {
    id: "logo-mark",
    category: "design",
    title: "Logo mark",
    description: "Minimal vector logo symbol on transparent background. Brand marks, favicons.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "minimal flat vector logo mark, the kind of geometric brand symbol you'd see in a modern identity system",
      composition: "one centered symbol built on a clean geometric grid, optically balanced with generous clear space around the silhouette",
      setting: "fully transparent background, isolated mark with no tile or container",
      color: "flat solid fills in one or two confident brand tones, no gradients, must also hold up as a single solid color",
      mood: "professional, timeless, distinctive, reduced to its essence",
      detail: "precise vector geometry with consistent line weight and corner radii, sharp scalable edges, a strong positive/negative silhouette that stays clear as a 16px favicon, clean cutout with no halos or fringing",
    },
    avoid: ["gradients", "3D bevels", "drop shadows", "photorealism", "text or lettering", "fussy fine detail", "halos or fringing", "watermark"],
  },
  {
    id: "ui-mockup",
    category: "design",
    title: "UI / app screen mockup",
    description: "Clean modern app or dashboard screen for portfolios and concept presentations.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "a screenshot of a real, shipped, modern app screen (not concept art or a wireframe)",
      composition: "a clear layout on an 8-point spacing grid with strong visual hierarchy — top nav or sidebar, content cards, and a primary action — generous gutters and consistent alignment",
      setting: "flat neutral canvas or a subtle realistic device frame, content edge-aligned with comfortable margins",
      color: "restrained modern UI palette: neutral greys and white surfaces with one confident accent color carrying the primary actions, plenty of whitespace",
      mood: "polished, professional, contemporary product design (think a well-funded SaaS dashboard)",
      detail: "a consistent component system, rounded cards with soft elevation shadows, clear typographic scale and legible realistic placeholder copy, pixel-clean alignment and even icon weights",
    },
    avoid: ["cluttered layout", "clashing or oversaturated colors", "lorem gibberish or garbled text", "skeuomorphism", "inconsistent spacing", "watermark"],
  },
  {
    id: "hero-banner",
    category: "design",
    title: "Website hero banner",
    description: "Wide abstract/illustrated hero background for landing pages.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "abstract website hero background graphic for a landing page",
      composition: "wide asymmetric composition with the visual weight pushed to one side, leaving a large calm copy-safe area of negative space for a headline and CTA — built so foreground text would sit cleanly with strong contrast",
      color: "a modern, brand-friendly palette built on harmonious tones with one accent, using a smooth multi-stop gradient or mesh rather than a flat fill — deliberately avoiding the clichéd blue-to-purple AI gradient",
      mood: "premium, modern, quietly energetic, uncluttered",
      detail: "smooth flowing shapes with soft layered depth, a faint film grain or subtle noise to kill banding, and a clean polished finish",
    },
    avoid: ["busy or crowded center", "text or lettering", "low-contrast clutter behind the copy area", "dated clip-art", "clichéd blue-purple AI gradient", "gradient banding", "watermark"],
  },
  {
    id: "social-card",
    category: "design",
    title: "Social / OG card",
    description: "Eye-catching square or landscape social graphic with room for a headline.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "bold editorial social / OG share card",
      composition: "one strong focal visual anchored off-center on a clear grid, with a confident copy-safe band of clear space reserved for a short headline, balanced to stay readable as a small feed thumbnail",
      color: "a distinctive editorial palette built around one confident accent color and clean neutrals — deliberately avoiding the clichéd blue-to-purple AI gradient",
      mood: "punchy, modern, editorial, on-brand",
      detail: "clean purposeful shapes with strong figure-ground separation, a single polished focal motif (not a generic clip-art icon), crisp and legible when scaled down to a feed thumbnail",
    },
    avoid: ["tiny details", "low contrast", "cluttered composition", "clichéd blue-purple gradient", "generic AI-slop gradient background", "cheap clip-art icons", "watermark"],
  },
  {
    id: "sticker",
    category: "design",
    title: "Die-cut sticker",
    description: "Glossy die-cut sticker with bold outline on transparent background.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "die-cut sticker illustration with a bold contour cut-line",
      composition: "one bold subject centered and filling the frame, wrapped in a thick even white die-cut border that traces the silhouette",
      setting: "fully transparent background, the sticker fully isolated",
      color: "vivid saturated fills with simple cel shading and clean flat highlights, one or two accent hues",
      mood: "fun, bold, playful",
      detail: "thick uniform white contour, glossy vinyl finish with a soft sheen, chunky confident shapes that stay readable at small size, clean crisp cutout edges with no halos or fringing",
    },
    avoid: ["fine intricate detail", "muted or washed-out colors", "photorealism", "background scenery or props", "thin broken outline", "halos or fringing", "watermark"],
  },
  {
    id: "seamless-pattern",
    category: "design",
    title: "Seamless repeating pattern",
    description: "Tileable surface pattern for backgrounds, packaging, textiles. Note: gpt-image approximates edge-matching; true 4-edge tiling isn't guaranteed.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "seamless repeating surface pattern tile",
      composition: "motifs distributed on a balanced repeat grid (half-drop or block) with even all-over density and no focal center, edges flowing off the frame so they wrap and tile cleanly on all four sides",
      color: "a cohesive limited palette of three to five harmonious tones with comfortable figure-ground contrast",
      mood: "decorative, cohesive, contemporary",
      detail: "consistent motif scale and spacing, edge-matched for a clean repeat, flat crisp shapes with even line weight",
    },
    avoid: ["a single centered subject", "visible seams or borders", "uneven or clumped density", "drifting motif scale", "watermark"],
  },
  {
    id: "texture-tileable",
    category: "design",
    title: "Tileable material texture",
    description: "Seamless material/surface texture (wood, marble, fabric) for 3D, web, mockups. Note: tiling is approximate, not guaranteed seam-free.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "seamless tileable material texture shot perfectly top-down (orthographic, flat to camera)",
      composition: "a uniform full-frame surface with no focal subject and even feature distribution, edges matched so the swatch tiles seamlessly",
      lighting: "flat even diffuse lighting, no directional shadows, no hotspots, so the tile reads consistently when repeated",
      color: "natural true-to-material color with realistic albedo and no color cast",
      detail: "fine realistic surface microdetail (grain, weave, veining or fibre as appropriate) at a consistent scale across the whole frame",
    },
    avoid: ["directional shadows", "visible seams", "vignetting or edge darkening", "a focal object", "perspective skew", "watermark"],
  },
  {
    id: "sticker-sheet",
    category: "design",
    title: "Sticker sheet (expression set)",
    description: "A set of sticker variants (poses/expressions) of one character on transparent bg.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a sticker sheet of one character in several poses and expressions",
      composition: "a tidy evenly-spaced grid of 4–6 die-cut variants of the same character, consistent sizing and equal gutters, each sticker reading as its own isolated cutout",
      setting: "fully transparent background behind every sticker",
      color: "vivid saturated fills with simple cel shading, one consistent palette shared across the whole set",
      mood: "fun, expressive, cohesive set",
      detail: "a thick even white contour on each sticker, identical character design and proportions across every pose, glossy finish, crisp clean cutout edges with no halos or fringing",
    },
    avoid: ["inconsistent or drifting character design", "background scenery", "photorealism", "uneven spacing or sizing", "halos or fringing", "watermark"],
  },
  {
    id: "neon-sign",
    category: "design",
    title: "Neon sign",
    description: "Glowing neon-tube sign/lettering against a dark wall. Logos, headers, decor.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "glowing bent glass neon-tube sign",
      composition: "the neon sign or word centered with a generous dark surround, the tubing drawn as a continuous confident stroke",
      setting: "dark matte wall or brick, with soft colored glow spilling onto the surface and a faint mounting-bracket hint",
      lighting: "luminous neon glow as the sole light source, realistic bloom, halation and colored light cast onto the wall",
      color: "one or two vivid neon hues against deep near-black darkness, high contrast and strong saturation",
      mood: "nightlife, retro, vibrant",
      detail: "realistic glass-tube core with a bright inner line and soft outer gradient halo, subtle reflections on the wall, a believable faint flicker feel",
    },
    avoid: ["flat daylight", "dull or desaturated colors", "missing or weak glow", "broken inconsistent tubing", "watermark"],
  },
];
