import type { Preset } from "../types.js";

export const design: Preset[] = [
  {
    id: "app-icon",
    category: "design",
    title: "App icon",
    description: "Polished rounded-square app icon with depth. iOS/Android/store-ready look.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "modern app icon design",
      composition: "single bold centered symbol on a rounded-square tile, balanced padding, scalable and legible at small sizes",
      setting: "smooth tile background, optional subtle gradient",
      lighting: "soft top light with a gentle long shadow for depth",
      color: "confident two- or three-color scheme with strong contrast",
      mood: "clean, premium, instantly recognizable",
      detail: "crisp geometry, smooth edges, simple memorable mark",
    },
    avoid: ["tiny intricate details", "text", "photorealism", "cluttered symbolism", "watermark"],
  },
  {
    id: "logo-mark",
    category: "design",
    title: "Logo mark",
    description: "Minimal vector logo symbol on transparent background. Brand marks, favicons.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "minimal flat vector logo mark",
      composition: "single centered geometric symbol, perfectly balanced, lots of clear space",
      setting: "fully transparent background",
      color: "flat solid colors, one or two tones, no gradients",
      mood: "professional, timeless, distinctive",
      detail: "clean geometric vector shapes, even line weight, sharp scalable edges, works in one color",
    },
    avoid: ["gradients", "3D bevels", "drop shadows", "photorealism", "text", "fine detail", "watermark"],
  },
  {
    id: "ui-mockup",
    category: "design",
    title: "UI / app screen mockup",
    description: "Clean modern app or dashboard screen for portfolios and concept presentations.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "clean modern UI design mockup of an app screen",
      composition: "well-structured layout with clear hierarchy, cards, navigation, realistic spacing and grid",
      setting: "flat neutral canvas or subtle device frame",
      color: "tasteful modern UI palette with one accent color, ample whitespace",
      mood: "polished, professional, contemporary product design",
      detail: "consistent components, rounded cards, legible placeholder type, soft shadows, pixel-clean alignment",
    },
    avoid: ["cluttered layout", "clashing colors", "lorem gibberish text", "skeuomorphism", "watermark"],
  },
  {
    id: "hero-banner",
    category: "design",
    title: "Website hero banner",
    description: "Wide abstract/illustrated hero background for landing pages.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "abstract website hero background graphic",
      composition: "wide composition with a clear area of calm negative space for headline text, visual interest toward one side",
      color: "modern brand-friendly gradient or palette, harmonious tones",
      mood: "premium, modern, energetic but uncluttered",
      detail: "smooth shapes, soft depth, subtle texture or grain, polished finish",
    },
    avoid: ["busy center", "text", "low contrast clutter", "dated clip-art", "watermark"],
  },
  {
    id: "social-card",
    category: "design",
    title: "Social / OG card",
    description: "Eye-catching square or landscape social graphic with room for a headline.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "bold social media graphic",
      composition: "strong focal visual with clear space reserved for a short headline, balanced for thumbnails",
      color: "high-contrast, scroll-stopping palette",
      mood: "punchy, modern, on-brand",
      detail: "clean shapes, crisp at small sizes, strong figure-ground separation",
    },
    avoid: ["tiny details", "low contrast", "cluttered composition", "watermark"],
  },
  {
    id: "sticker",
    category: "design",
    title: "Die-cut sticker",
    description: "Glossy die-cut sticker with bold outline on transparent background.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "die-cut sticker illustration",
      composition: "single bold subject, centered, thick clean white border outline",
      setting: "fully transparent background",
      color: "vivid saturated colors, simple cel shading",
      mood: "fun, bold, playful",
      detail: "thick contour cut-line, glossy finish, crisp bold shapes, readable at small size",
    },
    avoid: ["fine intricate detail", "muted colors", "photorealism", "background scenery", "watermark"],
  },
  {
    id: "seamless-pattern",
    category: "design",
    title: "Seamless repeating pattern",
    description: "Tileable surface pattern for backgrounds, packaging, textiles.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "seamless repeating pattern tile",
      composition: "evenly distributed motifs that tile seamlessly on all four edges with no visible seams, balanced density",
      color: "cohesive limited palette",
      mood: "decorative, cohesive",
      detail: "consistent motif scale, edge-matched for perfect repeat, flat clean shapes",
    },
    avoid: ["a single centered subject", "visible seams or borders", "uneven density", "watermark"],
  },
  {
    id: "texture-tileable",
    category: "design",
    title: "Tileable material texture",
    description: "Seamless material/surface texture (wood, marble, fabric) for 3D, web, mockups.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "seamless tileable material texture, top-down flat",
      composition: "uniform full-frame surface with no focal subject, edge-matched to tile seamlessly",
      lighting: "flat even lighting with no directional shadows",
      color: "natural true-to-material color",
      detail: "photorealistic fine surface detail, consistent scale across the frame",
    },
    avoid: ["directional shadows", "visible seams", "vignetting", "a focal object", "watermark"],
  },
];
