import type { Preset } from "../types.js";

export const design: Preset[] = [
  {
    id: "app-icon",
    category: "design",
    title: "App icon",
    description: "Polished rounded-square app icon with depth. iOS/Android/store-ready look.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "modern app icon design",
      composition: "single bold centered symbol on a rounded-square tile, balanced padding, scalable and legible at small sizes",
      setting: "smooth tile background, optional subtle gradient",
      lighting: "soft top light with a gentle long shadow for depth",
      color: "confident two- or three-color scheme with strong contrast",
      mood: "clean, premium, instantly recognizable",
      detail: "crisp geometry, smooth edges, simple memorable mark",
    },
    avoid: ["tiny intricate details", "text", "photorealism", "cluttered symbolism", "watermark"],
  },
  {
    id: "logo-mark",
    category: "design",
    title: "Logo mark",
    description: "Minimal vector logo symbol on transparent background. Brand marks, favicons.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "minimal flat vector logo mark",
      composition: "single centered geometric symbol, perfectly balanced, lots of clear space",
      setting: "fully transparent background",
      color: "flat solid colors, one or two tones, no gradients",
      mood: "professional, timeless, distinctive",
      detail: "clean geometric vector shapes, even line weight, sharp scalable edges, crisp silhouette with no halos or fringing, works in one color",
    },
    avoid: ["gradients", "3D bevels", "drop shadows", "photorealism", "text", "fine detail", "halos or fringing", "watermark"],
  },
  {
    id: "ui-mockup",
    category: "design",
    title: "UI / app screen mockup",
    description: "Clean modern app or dashboard screen for portfolios and concept presentations.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "a screenshot of a real, shipped, modern app screen (not concept art or a wireframe)",
      composition: "well-structured layout with clear hierarchy, cards, navigation, realistic spacing and grid",
      setting: "flat neutral canvas or subtle device frame",
      color: "tasteful modern UI palette with one accent color, ample whitespace",
      mood: "polished, professional, contemporary product design",
      detail: "consistent components, rounded cards, legible placeholder type, soft shadows, pixel-clean alignment",
    },
    avoid: ["cluttered layout", "clashing colors", "lorem gibberish text", "skeuomorphism", "watermark"],
  },
  {
    id: "hero-banner",
    category: "design",
    title: "Website hero banner",
    description: "Wide abstract/illustrated hero background for landing pages.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "abstract website hero background graphic",
      composition: "wide composition with a clear area of calm negative space for headline text, visual interest toward one side",
      color: "modern brand-friendly gradient or palette, harmonious tones",
      mood: "premium, modern, energetic but uncluttered",
      detail: "smooth shapes, soft depth, subtle texture or grain, polished finish",
    },
    avoid: ["busy center", "text", "low contrast clutter", "dated clip-art", "watermark"],
  },
  {
    id: "social-card",
    category: "design",
    title: "Social / OG card",
    description: "Eye-catching square or landscape social graphic with room for a headline.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "bold editorial social media graphic",
      composition: "one strong, well-crafted focal visual with confident clear space reserved for a short headline, balanced for thumbnails",
      color: "a distinctive editorial palette built around one confident accent color and clean neutrals — deliberately avoid the clichéd blue-to-purple AI gradient",
      mood: "punchy, modern, editorial, on-brand",
      detail: "clean well-designed shapes, crisp at small sizes, strong figure-ground separation, a single polished focal motif (not a generic clip-art icon)",
    },
    avoid: ["tiny details", "low contrast", "cluttered composition", "clichéd blue-purple gradient", "generic AI-slop gradient background", "cheap clip-art icons", "watermark"],
  },
  {
    id: "sticker",
    category: "design",
    title: "Die-cut sticker",
    description: "Glossy die-cut sticker with bold outline on transparent background.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "die-cut sticker illustration",
      composition: "single bold subject, centered, thick clean white border outline",
      setting: "fully transparent background",
      color: "vivid saturated colors, simple cel shading",
      mood: "fun, bold, playful",
      detail: "thick contour cut-line, glossy finish, crisp bold shapes with clean edges and no halos or fringing, readable at small size",
    },
    avoid: ["fine intricate detail", "muted colors", "photorealism", "background scenery", "halos or fringing", "watermark"],
  },
  {
    id: "seamless-pattern",
    category: "design",
    title: "Seamless repeating pattern",
    description: "Tileable surface pattern for backgrounds, packaging, textiles. Note: gpt-image approximates edge-matching; true 4-edge tiling isn't guaranteed.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "seamless repeating pattern tile",
      composition: "evenly distributed motifs that tile seamlessly on all four edges with no visible seams, balanced density",
      color: "cohesive limited palette",
      mood: "decorative, cohesive",
      detail: "consistent motif scale, edge-matched for perfect repeat, flat clean shapes",
    },
    avoid: ["a single centered subject", "visible seams or borders", "uneven density", "watermark"],
  },
  {
    id: "texture-tileable",
    category: "design",
    title: "Tileable material texture",
    description: "Seamless material/surface texture (wood, marble, fabric) for 3D, web, mockups. Note: tiling is approximate, not guaranteed seam-free.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "seamless tileable material texture, top-down flat",
      composition: "uniform full-frame surface with no focal subject, edge-matched to tile seamlessly",
      lighting: "flat even lighting with no directional shadows",
      color: "natural true-to-material color",
      detail: "photorealistic fine surface detail, consistent scale across the frame",
    },
    avoid: ["directional shadows", "visible seams", "vignetting", "a focal object", "watermark"],
  },
  {
    id: "sticker-sheet",
    category: "design",
    title: "Sticker sheet (expression set)",
    description: "A set of sticker variants (poses/expressions) of one character on transparent bg.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a sticker sheet of one character in several poses and expressions",
      composition: "a neat grid of 4–6 consistent variants of the same character, each a die-cut sticker",
      setting: "fully transparent background",
      color: "vivid saturated colors, simple cel shading",
      mood: "fun, expressive, cohesive set",
      detail: "thick white contour outline on each, consistent character design, crisp edges with no halos or fringing",
    },
    avoid: ["inconsistent character", "background scenery", "photorealism", "halos or fringing", "watermark"],
  },
  {
    id: "neon-sign",
    category: "design",
    title: "Neon sign",
    description: "Glowing neon-tube sign/lettering against a dark wall. Logos, headers, decor.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "glowing neon-tube sign",
      composition: "centered neon sign or word, generous dark surround",
      setting: "dark matte wall or brick with soft colored glow spill",
      lighting: "luminous neon glow with realistic bloom and reflections",
      color: "vivid neon hues against deep darkness, high contrast",
      mood: "nightlife, retro, vibrant",
      detail: "realistic glass-tube glow, gradient halos, subtle reflections, optional flicker feel",
    },
    avoid: ["flat daylight", "dull colors", "no glow", "watermark"],
  },
];
