import type { Preset } from "../types.js";

export const illustration: Preset[] = [
  {
    id: "flat-vector",
    category: "illustration",
    title: "Flat vector illustration",
    description: "Modern flat illustration with clean shapes. Marketing spots, empty states, blog headers.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "modern flat vector illustration",
      composition: "clear focal subject, balanced layout, generous negative space",
      setting: "simple abstract or minimal background shapes",
      color: "cohesive limited palette of 4–6 harmonious colors, subtle flat shading",
      mood: "friendly, contemporary, approachable",
      detail: "clean smooth shapes, consistent line weight, crisp edges, no gradients or photorealism",
    },
    avoid: ["photorealism", "harsh gradients", "drop shadows everywhere", "clip-art look", "watermark"],
  },
  {
    id: "line-art",
    category: "illustration",
    title: "Minimal line art",
    description: "Single-weight continuous line drawing. Logos marks, decorative accents, editorial.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "minimal single-weight line-art drawing",
      composition: "elegant continuous-line subject centered with lots of white space",
      setting: "plain white background",
      color: "monochrome, single ink color on white",
      mood: "refined, minimal, modern",
      detail: "consistent thin line weight, confident clean strokes, no shading or fill",
    },
    avoid: ["shading", "color fills", "varying line weights", "busy detail", "watermark"],
  },
  {
    id: "watercolor",
    category: "illustration",
    title: "Watercolor painting",
    description: "Soft watercolor with bleeding washes and paper texture. Editorial, cards, gentle hero art.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "delicate watercolor painting",
      composition: "loose painterly subject with soft edges fading into the paper",
      setting: "subtle washes, plenty of breathing room",
      lighting: "soft natural light implied through translucent layers",
      color: "soft translucent washes, gentle color bleeds, light palette",
      mood: "calm, organic, handmade",
      detail: "visible cold-press paper texture, granulation, wet-on-wet bleeds, white paper highlights",
    },
    avoid: ["hard digital edges", "flat fills", "neon colors", "photorealism", "watermark"],
  },
  {
    id: "oil-painting",
    category: "illustration",
    title: "Oil painting",
    description: "Rich textured oil painting with visible brushwork. Portraits, classical scenes.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "classical oil painting",
      composition: "painterly composition with strong focal subject",
      lighting: "dramatic chiaroscuro lighting, deep shadows and luminous highlights",
      color: "rich layered oil tones, warm varnished palette",
      mood: "timeless, dramatic, museum-quality",
      detail: "visible impasto brushstrokes, canvas texture, blended transitions",
    },
    avoid: ["flat digital look", "sharp vector edges", "cartoonish", "watermark"],
  },
  {
    id: "childrens-book",
    category: "illustration",
    title: "Children's book illustration",
    description: "Warm, whimsical storybook art. Kids content, friendly mascots, gentle scenes.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "hand-painted children's picture-book illustration with rich watercolor-and-gouache texture, in the style of a beautifully crafted modern award-winning picture book",
      composition: "charming storybook scene with an endearing, characterful central character and a sense of gentle narrative",
      setting: "cozy, imaginative, lovingly detailed environment",
      lighting: "soft warm storybook light with a gentle ambient glow",
      color: "rich harmonious hand-mixed palette with painterly depth and layered shading, not flat",
      mood: "playful, heartwarming, tender",
      detail: "visible brush and paper texture, characterful hand-drawn linework, expressive faces, crafted artisanal feel with storybook depth",
    },
    avoid: ["scary or harsh elements", "photorealism", "cluttered scene", "flat generic vector look", "stiff symmetrical AI-generated look", "garish oversaturated colors", "watermark"],
  },
  {
    id: "comic-manga",
    category: "illustration",
    title: "Comic / manga panel",
    description: "Bold inked comic or manga style with dynamic energy. Characters, action, covers.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "bold comic-book / manga illustration",
      composition: "dynamic action pose or framing, strong perspective",
      lighting: "high-contrast cel lighting with crisp shadow shapes",
      color: "vivid saturated cel shading, bold ink outlines",
      mood: "energetic, dramatic, stylized",
      detail: "clean confident inking, speed lines or impact accents where fitting, halftone texture",
    },
    avoid: ["muddy colors", "photorealism", "soft painterly blur", "watermark"],
  },
  {
    id: "concept-art",
    category: "illustration",
    title: "Concept art",
    description: "Cinematic painted concept art for worlds, characters, environments.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "cinematic digital concept art",
      composition: "epic establishing composition with strong depth and scale cues",
      setting: "richly imagined environment with atmospheric perspective",
      lighting: "dramatic cinematic lighting, volumetric god rays, strong mood",
      color: "filmic color grade, controlled value structure",
      mood: "epic, immersive, atmospheric",
      detail: "painterly rendered detail, believable materials, sense of grand scale",
    },
    avoid: ["flat lighting", "clip-art look", "muddy values", "watermark"],
  },
  {
    id: "gouache",
    category: "illustration",
    title: "Gouache / matte painting",
    description: "Matte gouache with chalky texture and flat-ish shapes. Posters, travel art, editorial.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "gouache illustration",
      composition: "stylized shapes with deliberate simplification, poster-like layout",
      lighting: "soft graphic lighting with clear value blocks",
      color: "muted matte palette, chalky opaque color",
      mood: "nostalgic, crafted, editorial",
      detail: "visible brush texture, slightly grainy matte finish, layered flat shapes",
    },
    avoid: ["glossy digital sheen", "photorealism", "neon colors", "text or lettering", "garbled text", "watermark"],
  },
  {
    id: "risograph",
    category: "illustration",
    title: "Risograph print",
    description: "Retro riso look: 2–3 spot inks, grain, slight misregistration. Zines, posters, merch.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "risograph print illustration",
      composition: "bold graphic shapes, poster-style layout",
      color: "two to three spot ink colors with overprint blends, limited palette",
      mood: "retro, indie, tactile",
      detail: "visible paper grain, halftone dithering, slight ink misregistration, textured overprint",
    },
    avoid: ["smooth gradients", "full-color photorealism", "clean digital edges", "watermark"],
  },
  {
    id: "ink-wash",
    category: "illustration",
    title: "Ink wash (sumi-e)",
    description: "East-Asian brush-and-ink painting with expressive strokes and empty space.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "traditional East-Asian ink wash painting (sumi-e)",
      composition: "spare, asymmetric composition with abundant empty space",
      lighting: "implied through ink density and untouched paper",
      color: "monochrome black ink with subtle grey washes on off-white rice paper",
      mood: "meditative, spontaneous, elegant",
      detail: "expressive confident brushstrokes, gradated ink tone, dry-brush texture, visible paper",
    },
    avoid: ["hard digital edges", "full color", "photorealism", "clutter", "watermark"],
  },
  {
    id: "pop-art",
    category: "illustration",
    title: "Pop art",
    description: "Bold 1960s pop-art with Ben-Day dots and flat saturated color. Posters, merch.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "bold pop-art illustration",
      composition: "graphic, iconic framing with strong figure-ground contrast",
      color: "flat saturated primary colors, bold black outlines, Ben-Day halftone dots",
      mood: "punchy, retro, playful",
      detail: "thick clean outlines, halftone dot shading, comic-print texture",
    },
    avoid: ["soft gradients", "photorealism", "muted palette", "fine rendering", "watermark"],
  },
  {
    id: "ukiyo-e",
    category: "illustration",
    title: "Ukiyo-e woodblock",
    description: "Japanese woodblock-print aesthetic with flat color and outlined forms.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "Japanese ukiyo-e woodblock print",
      composition: "flattened perspective, decorative arrangement, bold outlined shapes",
      color: "flat muted natural pigments, limited traditional palette",
      mood: "serene, classical, decorative",
      detail: "fine outlining, flat color fields, subtle woodgrain and paper texture, gradient skies",
    },
    avoid: ["western perspective realism", "photorealism", "neon color", "watermark"],
  },
  {
    id: "papercraft",
    category: "illustration",
    title: "Papercraft / paper-cut",
    description: "Layered cut-paper collage with soft shadows and tactile depth. Editorial, kids.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "layered cut-paper papercraft illustration",
      composition: "stacked paper layers creating depth, clean shapes",
      lighting: "soft directional light casting gentle drop shadows between paper layers",
      color: "matte construction-paper colors, cohesive palette",
      mood: "tactile, crafted, charming",
      detail: "visible paper edges and fibers, layered cut-out shapes, soft realistic shadows",
    },
    avoid: ["flat 2D vector look", "photorealism", "glossy surfaces", "watermark"],
  },
  {
    id: "charcoal-sketch",
    category: "illustration",
    title: "Charcoal sketch",
    description: "Expressive black-and-white charcoal drawing with smudged tones. Studies, portraits.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "charcoal sketch on textured paper",
      composition: "gestural drawing with a clear focal subject and loose edges",
      lighting: "dramatic value contrast built from smudged charcoal",
      color: "monochrome charcoal greys and deep blacks on toned paper",
      mood: "raw, expressive, studied",
      detail: "visible charcoal strokes, smudging and blending, paper tooth, white chalk highlights",
    },
    avoid: ["color", "clean digital lines", "photorealism", "flat shading", "watermark"],
  },
];
