import type { Preset } from "../types.js";

export const illustration: Preset[] = [
  {
    id: "flat-vector",
    category: "illustration",
    title: "Flat vector illustration",
    description: "Modern flat illustration with clean shapes. Marketing spots, empty states, blog headers.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "modern flat vector illustration built from clean geometric shapes and smooth bezier curves with crisp vector edges",
      composition: "single clear focal subject on a balanced asymmetric grid, generous negative space, deliberate visual hierarchy",
      setting: "minimal background of simple geometric shapes or a single flat field of color, no scene clutter",
      color: "cohesive limited palette of 4 to 6 analogous-plus-accent colors, flat fills with at most one subtle tonal step per shape, no rendered gradients",
      mood: "friendly, contemporary, confident and approachable",
      detail: "clean smooth silhouettes, consistent rounded line weight, crisp anti-aliased edges, optional fine grain texture overlay, no photorealism",
    },
    avoid: ["photorealism", "rendered gradients and meshes", "heavy drop shadows on every shape", "clip-art and stock-icon look", "gradient bevels", "watermark"],
  },
  {
    id: "line-art",
    category: "illustration",
    title: "Minimal line art",
    description: "Single-weight continuous line drawing. Logos marks, decorative accents, editorial.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "minimal single-weight line-art drawing, one unbroken continuous contour line with smooth open curves",
      composition: "elegant continuous-line subject centered with abundant white space and a calm, balanced silhouette",
      setting: "plain flat white background, no scene elements",
      color: "monochrome, a single ink color (warm black or deep charcoal) on white",
      mood: "refined, minimal, quietly modern",
      detail: "perfectly uniform thin line weight, confident unhesitating strokes, clean intersections, no shading, hatching, or fill",
    },
    avoid: ["shading or hatching", "color fills", "tapering or varying line weights", "broken or sketchy double lines", "busy detail", "watermark"],
  },
  {
    id: "watercolor",
    category: "illustration",
    title: "Watercolor painting",
    description: "Soft watercolor with bleeding washes and paper texture. Editorial, cards, gentle hero art.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "delicate wet-on-wet watercolor painting with translucent layered glazes and soft blooming edges",
      composition: "loose painterly subject with soft lost-and-found edges dissolving into the paper, off-center and breathing",
      setting: "subtle pale washes and untouched paper around the subject, plenty of open negative space",
      lighting: "soft diffuse natural light implied by luminous translucent layering and reserved paper whites",
      color: "soft transparent washes in a limited harmonious palette, gentle wet color bleeds and feathered gradients, no opaque flats",
      mood: "calm, organic, handmade and airy",
      detail: "visible cold-press paper tooth, granulating pigment settling in the texture, soft cauliflower blooms, backruns, and crisp reserved white highlights",
    },
    avoid: ["hard digital edges", "flat opaque fills", "neon or oversaturated colors", "uniform mechanical gradients", "photorealism", "watermark"],
  },
  {
    id: "oil-painting",
    category: "illustration",
    title: "Oil painting",
    description: "Rich textured oil painting with visible brushwork. Portraits, classical scenes.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "classical oil painting in the old-master tradition, alla prima brushwork over a toned ground with glazed shadows",
      composition: "painterly composition with a strong focal subject, golden-ratio placement and a clear path of light through the frame",
      lighting: "dramatic chiaroscuro with a single directional key light, deep transparent shadows and luminous warm highlights",
      color: "rich layered oil tones in a restrained warm earth palette of ochres, umbers and lead-white, mellow varnished glow",
      mood: "timeless, dramatic, contemplative",
      detail: "visible impasto in the lights with thinly scumbled darks, loaded-brush texture catching the light, woven canvas tooth, soft sfumato transitions",
    },
    avoid: ["flat digital look", "sharp vector edges", "cartoonish proportions", "plastic airbrushed skin", "watermark"],
  },
  {
    id: "childrens-book",
    category: "illustration",
    title: "Children's book illustration",
    description: "Warm, whimsical storybook art. Kids content, friendly mascots, gentle scenes.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "hand-painted children's picture-book illustration combining soft watercolor washes with opaque gouache highlights and delicate colored-pencil linework",
      composition: "charming storybook scene with one endearing, characterful protagonist, clear staging and a sense of gentle unfolding narrative",
      setting: "cozy, imaginative environment lovingly detailed with small storytelling props, soft rounded forms, friendly scale",
      lighting: "soft warm storybook light with a gentle ambient glow and tender rim light around the character",
      color: "rich harmonious hand-mixed palette with painterly depth and layered glazed shading, warm and inviting, never flat",
      mood: "playful, heartwarming, tender",
      detail: "visible brush and paper texture, characterful slightly wobbly hand-drawn linework, expressive readable faces, artisanal handmade feel with real depth",
    },
    avoid: ["scary or harsh elements", "photorealism", "cluttered overstuffed scene", "flat generic vector look", "stiff symmetrical computer-perfect rendering", "garish oversaturated colors", "dead empty staring eyes", "watermark"],
  },
  {
    id: "comic-manga",
    category: "illustration",
    title: "Comic / manga panel",
    description: "Bold inked comic or manga style with dynamic energy. Characters, action, covers.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "bold inked comic-book and manga illustration with confident brush-pen linework and screentone shading",
      composition: "dynamic action pose with foreshortening and a low or canted dramatic camera angle, strong dynamic perspective",
      lighting: "high-contrast cel lighting with crisp hard-edged shadow shapes and a bright key highlight",
      color: "vivid saturated cel shading in flat color blocks with bold variable-weight ink outlines and spotted blacks",
      mood: "energetic, dramatic, stylized",
      detail: "clean confident inking with tapering line weights, motion speed lines and impact bursts where fitting, halftone and screentone texture",
    },
    avoid: ["muddy desaturated colors", "photorealism", "soft painterly blur", "weak thin uniform outlines", "watermark"],
  },
  {
    id: "concept-art",
    category: "illustration",
    title: "Concept art",
    description: "Cinematic painted concept art for worlds, characters, environments.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "cinematic digital concept art, painterly matte-painting render with confident blocked brushwork over photo-real values",
      composition: "epic establishing wide shot with layered foreground, midground and background, strong leading lines and tiny figures for scale",
      setting: "richly imagined environment receding through atmospheric perspective into hazy depth",
      lighting: "dramatic cinematic key light with volumetric god rays raking through atmosphere, strong mood and clear time of day",
      color: "filmic color grade with a controlled complementary value structure, cool shadows against a warm light source",
      mood: "epic, immersive, atmospheric",
      detail: "painterly rendered detail that sharpens at the focal point and softens into the distance, believable physically-grounded materials, grand sense of scale",
    },
    avoid: ["flat even lighting", "clip-art look", "muddy compressed values", "wallpaper symmetry", "watermark"],
  },
  {
    id: "gouache",
    category: "illustration",
    title: "Gouache / matte painting",
    description: "Matte gouache with chalky texture and flat-ish shapes. Posters, travel art, editorial.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "gouache illustration with opaque matte layering and visible dry-brush drag over a toned ground",
      composition: "stylized simplified shapes with deliberate mid-century flattening and a clean poster-like layout",
      lighting: "soft graphic lighting resolved into a few clear value blocks rather than smooth gradients",
      color: "muted chalky palette of desaturated earthy tones, opaque flat color with subtle hand-mixed variation",
      mood: "nostalgic, crafted, editorial",
      detail: "visible directional brush texture, slightly grainy matte finish, layered opaque shapes with soft scumbled edges",
    },
    avoid: ["glossy digital sheen", "photorealism", "neon colors", "smooth airbrushed gradients", "text or lettering", "garbled text", "watermark"],
  },
  {
    id: "risograph",
    category: "illustration",
    title: "Risograph print",
    description: "Retro riso look: 2–3 spot inks, grain, slight misregistration. Zines, posters, merch.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "risograph print illustration with soy-ink spot colors layered as separate screens",
      composition: "bold flat graphic shapes in a confident poster-style layout with strong figure-ground",
      color: "two or three bright riso spot inks (such as fluorescent pink, federal blue and a warm yellow) building multiply overprint blends, deliberately limited palette",
      mood: "retro, indie, tactile",
      detail: "coarse visible paper grain, halftone and grit dithering, slight off-register channel shift, mottled uneven ink coverage and textured overprint",
    },
    avoid: ["smooth blended gradients", "full-color photorealism", "clean perfectly-registered digital edges", "more than three ink colors", "watermark"],
  },
  {
    id: "ink-wash",
    category: "illustration",
    title: "Ink wash (sumi-e)",
    description: "East-Asian brush-and-ink painting with expressive strokes and empty space.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "traditional East-Asian ink wash painting (sumi-e) with a soft loaded bamboo brush on absorbent paper",
      composition: "spare asymmetric composition with abundant empty negative space, the subject weighted to one side in classical balance",
      lighting: "form and light implied purely through ink density gradients and untouched white paper",
      color: "monochrome black ink graded from deep saturated blacks to delicate pale grey washes on off-white rice paper",
      mood: "meditative, spontaneous, elegant",
      detail: "expressive confident single-stroke brushwork with natural tonal gradation, feathered bleeds, dry-brush flying-white streaks, visible paper fibre",
    },
    avoid: ["hard digital edges", "full color", "photorealism", "fussy overworked detail", "clutter", "watermark"],
  },
  {
    id: "pop-art",
    category: "illustration",
    title: "Pop art",
    description: "Bold 1960s pop-art with Ben-Day dots and flat saturated color. Posters, merch.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "bold 1960s pop-art illustration in the silkscreen comic-print tradition",
      composition: "graphic iconic close-cropped framing with strong figure-ground contrast and a single dominant subject",
      color: "flat saturated primary colors (cyan, red, yellow) against bold black outlines, shading rendered as even Ben-Day halftone dots",
      mood: "punchy, retro, playful",
      detail: "thick clean uniform outlines, regular Ben-Day dot screens for tone, slight print misregistration and comic-newsprint texture",
    },
    avoid: ["soft blended gradients", "photorealism", "muted or pastel palette", "fine painterly rendering", "watermark"],
  },
  {
    id: "ukiyo-e",
    category: "illustration",
    title: "Ukiyo-e woodblock",
    description: "Japanese woodblock-print aesthetic with flat color and outlined forms.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "Japanese ukiyo-e woodblock print pulled from carved keyblock and color blocks on washi paper",
      composition: "flattened bird's-eye perspective with decorative diagonal arrangement and bold outlined silhouettes, asymmetric framing",
      color: "flat muted mineral and plant pigments in a limited traditional palette, indigo, vermilion, ochre and soft greens",
      mood: "serene, classical, decorative",
      detail: "fine even keyline outlining, flat unmodulated color fields, subtle bokashi gradient skies, visible woodgrain and laid-paper texture",
    },
    avoid: ["western single-point perspective realism", "photorealism", "neon or synthetic color", "cast shadows and 3D shading", "watermark"],
  },
  {
    id: "papercraft",
    category: "illustration",
    title: "Papercraft / paper-cut",
    description: "Layered cut-paper collage with soft shadows and tactile depth. Editorial, kids.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "layered cut-paper and paper-collage illustration, hand-cut shapes assembled in stacked planes",
      composition: "stacked paper layers building real depth from foreground to background, clean simplified shapes",
      lighting: "soft directional studio light casting gentle realistic drop shadows in the gaps between paper layers",
      color: "matte construction- and pastel-paper colors in a cohesive palette, with slight tonal shifts between layers",
      mood: "tactile, crafted, charming",
      detail: "visible cut paper edges and fibrous tooth, subtle curl and bend in the sheets, layered cut-out silhouettes, soft believable contact shadows",
    },
    avoid: ["flat 2D vector look", "photorealism", "glossy or reflective surfaces", "painted-on fake shadows", "watermark"],
  },
  {
    id: "charcoal-sketch",
    category: "illustration",
    title: "Charcoal sketch",
    description: "Expressive black-and-white charcoal drawing with smudged tones. Studies, portraits.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "vine and compressed charcoal drawing on textured toned paper, worked with stump and kneaded eraser",
      composition: "gestural life-drawing with a clear focal subject, energetic loose edges and unfinished margins",
      lighting: "dramatic value contrast built by layering and smudging charcoal, strong directional key light",
      color: "monochrome range of soft charcoal greys to dense velvety blacks on warm toned paper",
      mood: "raw, expressive, studied",
      detail: "visible directional charcoal strokes, smudged blended passages, eraser-lifted highlights, gritty paper tooth catching the chalk, white chalk accents",
    },
    avoid: ["color", "clean digital lines", "photorealism", "even flat airbrushed shading", "watermark"],
  },
];
