import type { Preset } from "../types.js";

export const illustration: Preset[] = [
  {
    id: "flat-vector",
    category: "illustration",
    title: "Flat vector illustration",
    description: "Modern flat illustration with clean shapes. Marketing spots, empty states, blog headers.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "modern flat vector illustration",
      composition: "clear focal subject, balanced layout, generous negative space",
      setting: "simple abstract or minimal background shapes",
      color: "cohesive limited palette of 4–6 harmonious colors, subtle flat shading",
      mood: "friendly, contemporary, approachable",
      detail: "clean smooth shapes, consistent line weight, crisp edges, no gradients or photorealism",
    },
    avoid: ["photorealism", "harsh gradients", "drop shadows everywhere", "clip-art look", "watermark"],
  },
  {
    id: "line-art",
    category: "illustration",
    title: "Minimal line art",
    description: "Single-weight continuous line drawing. Logos marks, decorative accents, editorial.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "minimal single-weight line-art drawing",
      composition: "elegant continuous-line subject centered with lots of white space",
      setting: "plain white background",
      color: "monochrome, single ink color on white",
      mood: "refined, minimal, modern",
      detail: "consistent thin line weight, confident clean strokes, no shading or fill",
    },
    avoid: ["shading", "color fills", "varying line weights", "busy detail", "watermark"],
  },
  {
    id: "watercolor",
    category: "illustration",
    title: "Watercolor painting",
    description: "Soft watercolor with bleeding washes and paper texture. Editorial, cards, gentle hero art.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "delicate watercolor painting",
      composition: "loose painterly subject with soft edges fading into the paper",
      setting: "subtle washes, plenty of breathing room",
      lighting: "soft natural light implied through translucent layers",
      color: "soft translucent washes, gentle color bleeds, light palette",
      mood: "calm, organic, handmade",
      detail: "visible cold-press paper texture, granulation, wet-on-wet bleeds, white paper highlights",
    },
    avoid: ["hard digital edges", "flat fills", "neon colors", "photorealism", "watermark"],
  },
  {
    id: "oil-painting",
    category: "illustration",
    title: "Oil painting",
    description: "Rich textured oil painting with visible brushwork. Portraits, classical scenes.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "classical oil painting",
      composition: "painterly composition with strong focal subject",
      lighting: "dramatic chiaroscuro lighting, deep shadows and luminous highlights",
      color: "rich layered oil tones, warm varnished palette",
      mood: "timeless, dramatic, museum-quality",
      detail: "visible impasto brushstrokes, canvas texture, blended transitions",
    },
    avoid: ["flat digital look", "sharp vector edges", "cartoonish", "watermark"],
  },
  {
    id: "childrens-book",
    category: "illustration",
    title: "Children's book illustration",
    description: "Warm, whimsical storybook art. Kids content, friendly mascots, gentle scenes.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "warm whimsical children's-book illustration",
      composition: "charming storybook scene with an endearing central character",
      setting: "cozy, imaginative environment",
      lighting: "soft warm light, gentle ambient glow",
      color: "warm inviting palette, soft textured shading",
      mood: "playful, heartwarming, gentle",
      detail: "hand-painted texture, rounded friendly shapes, expressive characters",
    },
    avoid: ["scary or harsh elements", "photorealism", "cluttered scene", "watermark"],
  },
  {
    id: "comic-manga",
    category: "illustration",
    title: "Comic / manga panel",
    description: "Bold inked comic or manga style with dynamic energy. Characters, action, covers.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "bold comic-book / manga illustration",
      composition: "dynamic action pose or framing, strong perspective",
      lighting: "high-contrast cel lighting with crisp shadow shapes",
      color: "vivid saturated cel shading, bold ink outlines",
      mood: "energetic, dramatic, stylized",
      detail: "clean confident inking, speed lines or impact accents where fitting, halftone texture",
    },
    avoid: ["muddy colors", "photorealism", "soft painterly blur", "watermark"],
  },
  {
    id: "concept-art",
    category: "illustration",
    title: "Concept art",
    description: "Cinematic painted concept art for worlds, characters, environments.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "cinematic digital concept art",
      composition: "epic establishing composition with strong depth and scale cues",
      setting: "richly imagined environment with atmospheric perspective",
      lighting: "dramatic cinematic lighting, volumetric god rays, strong mood",
      color: "filmic color grade, controlled value structure",
      mood: "epic, immersive, atmospheric",
      detail: "painterly rendered detail, believable materials, sense of grand scale",
    },
    avoid: ["flat lighting", "clip-art look", "muddy values", "watermark"],
  },
  {
    id: "gouache",
    category: "illustration",
    title: "Gouache / matte painting",
    description: "Matte gouache with chalky texture and flat-ish shapes. Posters, travel art, editorial.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "gouache illustration",
      composition: "stylized shapes with deliberate simplification, poster-like layout",
      lighting: "soft graphic lighting with clear value blocks",
      color: "muted matte palette, chalky opaque color",
      mood: "nostalgic, crafted, editorial",
      detail: "visible brush texture, slightly grainy matte finish, layered flat shapes",
    },
    avoid: ["glossy digital sheen", "photorealism", "neon colors", "watermark"],
  },
  {
    id: "risograph",
    category: "illustration",
    title: "Risograph print",
    description: "Retro riso look: 2–3 spot inks, grain, slight misregistration. Zines, posters, merch.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "risograph print illustration",
      composition: "bold graphic shapes, poster-style layout",
      color: "two to three spot ink colors with overprint blends, limited palette",
      mood: "retro, indie, tactile",
      detail: "visible paper grain, halftone dithering, slight ink misregistration, textured overprint",
    },
    avoid: ["smooth gradients", "full-color photorealism", "clean digital edges", "watermark"],
  },
];
