import type { Preset } from "../types.js";

// Photographic styles. `subject` is supplied by the caller; these set medium, lighting, lens, etc.
export const photography: Preset[] = [
  {
    id: "product-studio",
    category: "photography",
    title: "Product studio shot",
    description: "Clean e-commerce product on a seamless backdrop. Best for catalog/hero product images.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "commercial studio product photograph, tabletop e-commerce style",
      composition: "centered hero with the product filling roughly 70% of the frame at a slight 15-degree high angle, generous breathing room on all sides",
      setting: "seamless light-grey sweep backdrop fading top-to-bottom, with a soft natural contact shadow grounding the product",
      lighting: "large feathered softbox key at 45 degrees, subtle gradient fill card opposite, and a thin rim light to separate the edges from the sweep",
      camera: "100mm macro lens at f/8, tack-sharp from the front face through to the back, no perspective distortion",
      color: "true-to-life color with neutral 5500K white balance and accurate material hues",
      mood: "premium, clean, considered commercial polish",
      detail: "crisp material micro-texture, clean specular highlights, no noise or compression artifacts",
    },
    avoid: ["busy background", "harsh clipped shadows", "watermark", "text overlay", "extra props unless requested"],
  },
  {
    id: "product-lifestyle",
    category: "photography",
    title: "Product lifestyle scene",
    description: "Product in a real, aspirational context (desk, kitchen, outdoors). For ads and social.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "lifestyle product photograph in an authentic in-use setting",
      composition: "product as the clear focal point on a rule-of-thirds intersection, leading lines from surrounding props, foreground context falling into shallow background",
      setting: "tasteful real-world environment relevant to the product (desk, kitchen counter, café table), props softly out of focus",
      lighting: "soft directional window light from camera-left, warm and inviting, gentle highlight roll-off with a bounce fill softening the shadows",
      camera: "50mm lens at f/2.0, creamy bokeh, product held in crisp focus on the front plane",
      color: "warm natural palette in a Kodak Portra 400 register with pleasing gentle contrast",
      mood: "aspirational, authentic, lived-in",
      detail: "authentic candid photograph with natural imperfections and real-world texture, believable everyday scene, not an over-polished CGI render",
    },
    avoid: ["cluttered scene", "distracting background objects", "over-saturation", "CGI render look", "artificial over-polished perfection", "watermark"],
  },
  {
    id: "food-overhead",
    category: "photography",
    title: "Food — overhead flat-lay",
    description: "Top-down food/table styling. Great for recipes, menus, and social posts.",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "overhead food photograph, editorial flat-lay styling",
      composition: "perfectly top-down 90-degree flat-lay, asymmetric balanced arrangement on a loose grid, generous negative space upper-left for copy, a few complementary props feathered at the edges",
      setting: "textured surface such as weathered rustic wood, honed stone, or rumpled linen",
      lighting: "soft diffused daylight raking from one side through a large diffusion scrim, gentle directional shadows with a white bounce for fill",
      camera: "35mm lens aimed straight down at f/5.6, even sharp focus across the full spread",
      color: "fresh, appetizing natural color with vibrant ingredients and accurate greens and reds",
      mood: "fresh, artisanal, editorial",
      detail: "appetizing surface texture, visible crumb and grain, steam or condensation cues where natural",
    },
    avoid: ["plastic-looking food", "messy plating", "harsh flash", "unnatural colors", "watermark"],
  },
  {
    id: "food-hero",
    category: "photography",
    title: "Food — hero close-up",
    description: "Close, three-quarter hero shot of a dish or drink. For headers and packaging.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "hero food photograph, close-up editorial style",
      composition: "three-quarter 45-degree close-up, the dish filling the frame with shallow background falloff and a clean diagonal lead-in",
      setting: "minimal styled tabletop against a dark moody backdrop, background softly defocused",
      lighting: "single large softbox as dramatic side light at a 4:1 ratio against the dark backdrop, with a small reflector lifting glossy specular highlights on sauces and glaze",
      camera: "90mm macro at f/2.8, razor-sharp on the front edge of the dish with rapid falloff behind",
      color: "rich saturated appetizing tones with deep controlled shadows",
      mood: "indulgent, premium, editorial",
      detail: "tight surface detail, glistening highlights on textures, crisp fresh garnish",
    },
    avoid: ["flat lighting", "dull colors", "clutter", "watermark"],
  },
  {
    id: "portrait-headshot",
    category: "photography",
    title: "Corporate headshot",
    description: "Clean professional portrait for team pages, LinkedIn, press.",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "professional corporate headshot photograph",
      composition: "head-and-shoulders framing, shoulders angled slightly off-axis with the face turned back to camera, eyes on the lens, eyeline on the upper third",
      setting: "smooth neutral studio background, softly graduated mid-grey falling off behind the shoulders",
      lighting: "large octabox key feathered at 45 degrees in soft loop lighting at a 3:1 ratio, a fill card opposite to open the shadow side, twin catchlights in the eyes",
      camera: "85mm portrait lens at f/2.8, sharp on the near eye with gentle background separation",
      color: "natural accurate skin tones, neutral restrained grade",
      mood: "confident, approachable, professional",
      detail: "sharp facial detail with natural skin texture and pores intact, no plastic over-retouching",
    },
    avoid: ["plastic skin", "harsh shadows", "distracting background", "wide-angle distortion", "watermark"],
  },
  {
    id: "portrait-environmental",
    category: "photography",
    title: "Environmental portrait",
    description: "Person in their context (workshop, studio, outdoors). Editorial, storytelling.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "environmental portrait photograph, editorial documentary style",
      composition: "subject placed off-center on a rule-of-thirds line within meaningful surroundings, medium-wide framing that lets the space breathe and tell the story",
      setting: "authentic working environment that reveals the subject (workshop, studio, field), context legible but softly out of focus",
      lighting: "natural directional window or doorway light, warm and characterful, shadows left to fall naturally for dimension",
      camera: "35mm lens at f/2.0, subject held sharp with the background gently blurred for separation",
      color: "filmic slightly warm grade with muted earthy tones",
      mood: "candid, human, narrative",
      detail: "raw documentary realism, natural skin with real texture and imperfections, rich authentic texture in clothing and setting, unstaged and lived-in",
    },
    avoid: ["studio sterility", "stiff posing", "blown highlights", "over-retouched plastic skin", "artificial perfection", "CGI render look", "watermark"],
  },
  {
    id: "fashion-editorial",
    category: "photography",
    title: "Fashion editorial",
    description: "High-fashion magazine look. Bold styling, strong pose, striking light.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "high-fashion editorial photograph, magazine spread style",
      composition: "full or three-quarter body in a dynamic confident pose, strong intentional negative space framing the figure",
      setting: "minimal seamless or boldly monochromatic set that complements the wardrobe palette",
      lighting: "dramatic hard-edged studio key with a beauty dish, crisp specular highlights and deliberate carved shadow shaping at a 4:1 ratio",
      camera: "medium-format body with an 80mm lens at f/5.6, immaculate edge-to-edge sharpness",
      color: "bold controlled color story with one dominant accent hue",
      mood: "striking, aspirational, avant-garde",
      detail: "clean fabric weave and drape detail, couture-grade finish on seams and texture",
    },
    avoid: ["snapshot feel", "cluttered styling", "muddy color", "watermark"],
  },
  {
    id: "real-estate-interior",
    category: "photography",
    title: "Real-estate interior",
    description: "Bright, wide interior for listings and architectural showcases.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "architectural interior photograph for a real-estate listing",
      composition: "wide one- or two-point perspective with dead-straight verticals, camera at chest height, tidy staged space leading the eye to a window or focal corner",
      setting: "well-appointed interior with tasteful, restrained furnishing and styling",
      lighting: "bright balanced daylight through windows blended with ambient interior fill, exposure-bracketed so windows hold detail and no highlights blow out",
      camera: "16–24mm tilt-shift lens at f/8, deep focus front to back, perspective corrected for parallel walls",
      color: "clean neutral white balance with true colors and no mixed-light color cast",
      mood: "bright, spacious, inviting",
      detail: "sharp throughout with realistic material surfaces, no lens distortion or bowed lines",
    },
    avoid: ["fisheye distortion", "tilted verticals", "clutter", "color casts", "watermark"],
  },
  {
    id: "architecture-exterior",
    category: "photography",
    title: "Architecture exterior",
    description: "Dramatic building/exterior shot for portfolios and hero banners.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "architectural exterior photograph",
      composition: "strong leading lines and balanced asymmetry, the building as hero set against open sky with room to breathe",
      setting: "clean uncluttered surroundings beneath a dramatic sky with structured clouds",
      lighting: "golden-hour or blue-hour light raking low across the façades to model depth and reveal material relief",
      camera: "24mm tilt-shift lens at f/11, verticals corrected dead-straight, deep front-to-back focus",
      color: "rich natural grade with deep saturated skies and warm façade tones",
      mood: "monumental, refined",
      detail: "crisp real material and structural detail, authentic architectural photograph with true-to-life concrete, glass and stone texture — a real photo, not a CGI render or 3D visualization",
    },
    avoid: ["keystoning", "flat midday light", "power lines clutter", "CGI render look", "3D-visualization look", "watermark"],
  },
  {
    id: "automotive",
    category: "photography",
    title: "Automotive hero",
    description: "Glossy car/vehicle hero with sculpted reflections. Ads, configurators.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "automotive hero photograph, advertising style",
      composition: "low three-quarter front angle near wheel height, vehicle filling the frame dynamically along a strong diagonal",
      setting: "clean studio cyc or moody location with carefully controlled reflections in the bodywork",
      lighting: "long overhead gradient softbox and large white reflector strips sculpting continuous highlight runs down the bodywork, defined specular lines on every panel edge",
      camera: "70mm lens at f/9, sharp throughout with a faint sense of motion energy",
      color: "deep contrast with accurate paint color and visible metallic flake in the highlights",
      mood: "powerful, premium, cinematic",
      detail: "clean unblemished paint, crisp coherent reflections, sharp wheels, tyres and badges",
    },
    avoid: ["messy reflections", "flat lighting", "distorted proportions", "watermark"],
  },
  {
    id: "macro",
    category: "photography",
    title: "Macro detail",
    description: "Extreme close-up of small subjects (jewelry, insects, textures).",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "macro photograph, extreme close-up detail study",
      composition: "extreme close-up with the subject filling the frame, a razor-thin plane of focus on the key detail and rapid falloff",
      setting: "softly defocused complementary background, a single clear point of interest",
      lighting: "soft diffused light from a small softbox or diffuser, delicate raking highlights revealing micro-texture",
      camera: "1:1 macro lens at f/4, smooth creamy bokeh, focus-stacked for sharpness across the subject's surface",
      color: "rich, true, accurate color",
      mood: "intimate, jewel-like",
      detail: "intricate micro-detail with dew droplets, fibers, or crystal facets clearly resolved",
    },
    avoid: ["flat focus", "harsh specular blowouts", "noise", "watermark"],
  },
  {
    id: "golden-hour-landscape",
    category: "photography",
    title: "Golden-hour landscape",
    description: "Sweeping landscape in warm low sun. Hero banners, backgrounds.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "landscape photograph",
      composition: "expansive vista with strong foreground anchor, layered mid-ground and background receding to the horizon for depth, horizon on a third",
      setting: "natural landscape with atmospheric aerial perspective fading toward the distance",
      lighting: "warm low golden-hour sun raking across the scene, long soft shadows, gentle haze and god rays through the air",
      camera: "24mm lens at f/11, hyperfocal deep focus front to back",
      color: "warm golden grade with rich but natural skies and lifted earthy mid-tones",
      mood: "serene, epic, cinematic",
      detail: "fine realistic landscape detail, crisp horizon, natural atmospheric haze — a genuine photograph with true photographic texture, not a painting or digital illustration",
    },
    avoid: ["flat midday light", "oversaturated HDR look", "muddy shadows", "painterly or illustrated look", "watermark"],
  },
  {
    id: "product-flatlay",
    category: "photography",
    title: "Product flat-lay",
    description: "Top-down styled arrangement of products/accessories. Social, editorial, e-commerce.",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "overhead product flat-lay photograph, styled editorial arrangement",
      composition: "perfectly top-down 90-degree view, objects arranged on a considered grid with balanced spacing and intentional negative space",
      setting: "clean styled surface such as matte art paper, honed marble, or pressed linen",
      lighting: "soft even diffused overhead light through a large scrim, minimal short soft shadows for a gentle sense of depth",
      camera: "35mm lens aimed straight down at f/5.6, evenly sharp across the whole frame",
      color: "cohesive curated palette with a limited set of harmonized hues",
      mood: "tidy, aspirational, editorial",
      detail: "crisp product detail with true material surfaces and considered, deliberate composition",
    },
    avoid: ["clutter", "harsh shadows", "tilted angle", "messy arrangement", "watermark"],
  },
  {
    id: "tilt-shift",
    category: "photography",
    title: "Tilt-shift miniature",
    description: "Miniature-faking tilt-shift look — scenes that resemble tiny models.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "tilt-shift miniature-effect photograph",
      composition: "high elevated vantage looking down on a busy scene, a narrow horizontal band of sharp focus across the subject with everything above and below thrown soft",
      lighting: "bright saturated midday daylight with crisp small shadows that sell the toy-model scale",
      camera: "tilt-shift lens with the front standard tilted for an extremely shallow wedge of focus, strong creamy top-and-bottom blur",
      color: "punchy saturated color with lifted contrast that enhances the toy-model illusion",
      mood: "playful, miniature, whimsical",
      detail: "tiny crisp detail in the focus band, smooth even blur falling off above and below",
    },
    avoid: ["uniform sharpness", "flat lighting", "muted color", "watermark"],
  },
  {
    id: "film-35mm",
    category: "photography",
    title: "35mm film",
    description: "Analog 35mm film look with grain and natural color. Nostalgic, candid, editorial.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "35mm analog film photograph",
      composition: "candid naturalistic framing with slightly imperfect, of-the-moment placement",
      lighting: "available natural light with gentle highlight roll-off and shadows that retain detail",
      camera: "shot on 35mm film with a 50mm lens at f/2.8, fine organic grain and a touch of halation around bright highlights",
      color: "warm Kodak Portra 400 palette with soft low contrast and slightly muted greens",
      mood: "nostalgic, authentic, timeless",
      detail: "fine film grain, organic emulsion texture, natural imperfections, no clinical digital edges",
    },
    avoid: ["clinical digital sharpness", "HDR look", "plastic skin", "watermark"],
  },
  {
    id: "double-exposure",
    category: "photography",
    title: "Double exposure",
    description: "Artistic blend of two images (often a silhouette filled with a scene). Posters, covers.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "in-camera double-exposure photograph, two overlaid frames",
      composition: "a bold profile silhouette whose interior is filled with a second blended scene, the second exposure densest inside the shape and fading toward the edges",
      lighting: "high-key contrast between the darker silhouette and a clean bright background, the inner scene lit so it reads through the shadow mass",
      color: "restrained two-tone palette so both layers stay legible, no muddy mixing",
      mood: "poetic, evocative, artful",
      detail: "seamless blend of the two exposures, a clean crisp silhouette edge, balanced overlay density",
    },
    avoid: ["muddy overlap", "busy background", "low contrast", "watermark"],
  },
];
