import type { Preset } from "../types.js";

// Photographic styles. `subject` is supplied by the caller; these set medium, lighting, lens, etc.
export const photography: Preset[] = [
  {
    id: "product-studio",
    category: "photography",
    title: "Product studio shot",
    description: "Clean e-commerce product on a seamless backdrop. Best for catalog/hero product images.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "professional studio product photograph",
      composition: "centered hero composition, product fills about 70% of the frame, slight high angle",
      setting: "seamless light-grey studio backdrop with a soft gradient and a subtle contact shadow",
      lighting: "soft three-point studio lighting, large softbox key, gentle rim light to separate edges",
      camera: "shot on a 100mm macro lens at f/8, tack-sharp focus, full depth across the product",
      color: "true-to-life color, neutral white balance",
      mood: "premium, clean, commercial",
      detail: "ultra-detailed, crisp material textures, no noise, no compression artifacts",
    },
    avoid: ["busy background", "harsh shadows", "watermark", "text overlay", "extra props unless requested"],
  },
  {
    id: "product-lifestyle",
    category: "photography",
    title: "Product lifestyle scene",
    description: "Product in a real, aspirational context (desk, kitchen, outdoors). For ads and social.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "lifestyle product photograph",
      composition: "product as the clear focal point, rule-of-thirds placement, natural surrounding context with shallow background",
      setting: "tasteful real-world environment relevant to the product, softly blurred",
      lighting: "soft natural window light, warm and inviting, gentle highlights",
      camera: "shot on a 50mm lens at f/2.0, creamy bokeh, product in sharp focus",
      color: "warm, natural palette with pleasing contrast",
      mood: "aspirational, authentic, lived-in",
      detail: "high detail on the product, realistic materials, believable scene",
    },
    avoid: ["cluttered scene", "distracting background objects", "over-saturation", "watermark"],
  },
  {
    id: "food-overhead",
    category: "photography",
    title: "Food — overhead flat-lay",
    description: "Top-down food/table styling. Great for recipes, menus, and social posts.",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "overhead food photograph",
      composition: "perfectly top-down flat-lay, balanced arrangement, generous negative space, a few complementary props at the edges",
      setting: "textured surface such as rustic wood, stone, or linen",
      lighting: "soft diffused daylight from one side, gentle natural shadows",
      camera: "shot straight down with a 35mm lens, even sharp focus across the spread",
      color: "fresh, appetizing, natural color with vibrant ingredients",
      mood: "fresh, artisanal, editorial",
      detail: "mouth-watering detail, visible texture, steam or freshness cues where natural",
    },
    avoid: ["plastic-looking food", "messy plating", "harsh flash", "unnatural colors", "watermark"],
  },
  {
    id: "food-hero",
    category: "photography",
    title: "Food — hero close-up",
    description: "Close, three-quarter hero shot of a dish or drink. For headers and packaging.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "hero food photograph",
      composition: "three-quarter close-up angle, dish fills the frame, shallow background falloff",
      setting: "minimal styled tabletop, softly defocused background",
      lighting: "dramatic soft side light with a dark backdrop, glossy highlights",
      camera: "shot on a 90mm macro at f/2.8, razor-sharp on the front of the dish",
      color: "rich, saturated, appetizing tones",
      mood: "indulgent, premium, editorial",
      detail: "extreme close detail, glistening textures, fresh garnish",
    },
    avoid: ["flat lighting", "dull colors", "clutter", "watermark"],
  },
  {
    id: "portrait-headshot",
    category: "photography",
    title: "Corporate headshot",
    description: "Clean professional portrait for team pages, LinkedIn, press.",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "professional corporate headshot photograph",
      composition: "head-and-shoulders framing, subject facing slightly off-axis, eyes on the lens",
      setting: "smooth neutral studio background, softly graduated grey or muted tone",
      lighting: "flattering soft key with a large softbox, subtle fill, catchlights in the eyes",
      camera: "shot on an 85mm portrait lens at f/2.8, sharp on the eyes, gentle background separation",
      color: "natural skin tones, neutral grade",
      mood: "confident, approachable, professional",
      detail: "sharp facial detail, natural skin texture, no over-retouching",
    },
    avoid: ["plastic skin", "harsh shadows", "distracting background", "wide-angle distortion", "watermark"],
  },
  {
    id: "portrait-environmental",
    category: "photography",
    title: "Environmental portrait",
    description: "Person in their context (workshop, studio, outdoors). Editorial, storytelling.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "environmental portrait photograph",
      composition: "subject placed off-center with meaningful surroundings, medium-wide framing",
      setting: "authentic environment that tells the subject's story, softly out of focus",
      lighting: "natural directional light, warm and characterful",
      camera: "shot on a 35mm lens at f/2.0, subject sharp, background gently blurred",
      color: "filmic, slightly warm grade",
      mood: "candid, human, narrative",
      detail: "rich texture in clothing and setting, lifelike skin",
    },
    avoid: ["studio sterility", "stiff posing", "blown highlights", "watermark"],
  },
  {
    id: "fashion-editorial",
    category: "photography",
    title: "Fashion editorial",
    description: "High-fashion magazine look. Bold styling, strong pose, striking light.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "high-fashion editorial photograph",
      composition: "full or three-quarter body, dynamic confident pose, intentional negative space",
      setting: "minimal or boldly colored set that complements the wardrobe",
      lighting: "dramatic studio lighting with crisp highlights and deliberate shadow shaping",
      camera: "shot on a medium-format camera, 80mm, f/5.6, immaculate sharpness",
      color: "bold, controlled color story",
      mood: "striking, aspirational, avant-garde",
      detail: "flawless fabric detail, couture finish",
    },
    avoid: ["snapshot feel", "cluttered styling", "muddy color", "watermark"],
  },
  {
    id: "real-estate-interior",
    category: "photography",
    title: "Real-estate interior",
    description: "Bright, wide interior for listings and architectural showcases.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "architectural interior photograph",
      composition: "wide one- or two-point perspective, straight verticals, tidy staged space",
      setting: "well-appointed interior with tasteful furnishing",
      lighting: "bright balanced daylight through windows, even ambient fill, no blown windows",
      camera: "shot on a 16–24mm tilt-shift lens, deep focus, corrected perspective",
      color: "clean neutral white balance, true colors",
      mood: "bright, spacious, inviting",
      detail: "sharp throughout, realistic materials, no distortion",
    },
    avoid: ["fisheye distortion", "tilted verticals", "clutter", "color casts", "watermark"],
  },
  {
    id: "architecture-exterior",
    category: "photography",
    title: "Architecture exterior",
    description: "Dramatic building/exterior shot for portfolios and hero banners.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "architectural exterior photograph",
      composition: "strong leading lines, balanced asymmetry, building as hero against sky",
      setting: "clean surroundings, dramatic sky",
      lighting: "golden-hour or blue-hour light raking across façades",
      camera: "shot on a 24mm tilt-shift, corrected verticals, deep sharp focus",
      color: "rich natural grade with deep skies",
      mood: "monumental, refined",
      detail: "crisp material and structural detail",
    },
    avoid: ["keystoning", "flat midday light", "power lines clutter", "watermark"],
  },
  {
    id: "automotive",
    category: "photography",
    title: "Automotive hero",
    description: "Glossy car/vehicle hero with sculpted reflections. Ads, configurators.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "automotive hero photograph",
      composition: "low three-quarter front angle, vehicle filling the frame dynamically",
      setting: "clean studio or moody location with controlled reflections",
      lighting: "large gradient softbox reflections sculpting the bodywork, defined highlight strips",
      camera: "shot on a 70mm lens at f/9, sharp throughout, slight motion energy",
      color: "deep contrast, accurate paint color with metallic flake",
      mood: "powerful, premium, cinematic",
      detail: "flawless paint, crisp reflections, sharp wheels and badges",
    },
    avoid: ["messy reflections", "flat lighting", "distorted proportions", "watermark"],
  },
  {
    id: "macro",
    category: "photography",
    title: "Macro detail",
    description: "Extreme close-up of small subjects (jewelry, insects, textures).",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "macro photograph",
      composition: "extreme close-up, subject filling the frame, razor-thin plane of focus",
      setting: "softly defocused background, single point of interest",
      lighting: "soft diffused light with delicate highlights revealing micro-texture",
      camera: "shot on a 1:1 macro lens at f/4, beautiful bokeh, focus-stacked sharpness on the subject",
      color: "rich, true color",
      mood: "intimate, jewel-like",
      detail: "intricate micro-detail, dew, fibers, or facets clearly visible",
    },
    avoid: ["flat focus", "harsh specular blowouts", "noise", "watermark"],
  },
  {
    id: "golden-hour-landscape",
    category: "photography",
    title: "Golden-hour landscape",
    description: "Sweeping landscape in warm low sun. Hero banners, backgrounds.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "landscape photograph",
      composition: "expansive vista, strong foreground interest, layered depth to the horizon",
      setting: "natural landscape with atmospheric depth",
      lighting: "warm golden-hour sun, long soft shadows, gentle haze and god rays",
      camera: "shot on a 24mm lens at f/11, deep focus front to back",
      color: "warm golden grade, rich but natural skies",
      mood: "serene, epic, cinematic",
      detail: "fine landscape detail, crisp horizon, natural atmosphere",
    },
    avoid: ["flat midday light", "oversaturated HDR look", "muddy shadows", "watermark"],
  },
  {
    id: "product-flatlay",
    category: "photography",
    title: "Product flat-lay",
    description: "Top-down styled arrangement of products/accessories. Social, editorial, e-commerce.",
    recommended: { size: "1024x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "overhead product flat-lay photograph",
      composition: "perfectly top-down, neatly arranged objects with balanced spacing and negative space",
      setting: "clean styled surface (paper, marble, or linen)",
      lighting: "soft even diffused light, minimal soft shadows",
      camera: "shot straight down, 35mm, sharp across the frame",
      color: "cohesive curated palette",
      mood: "tidy, aspirational, editorial",
      detail: "crisp product detail, true materials, considered composition",
    },
    avoid: ["clutter", "harsh shadows", "tilted angle", "messy arrangement", "watermark"],
  },
  {
    id: "tilt-shift",
    category: "photography",
    title: "Tilt-shift miniature",
    description: "Miniature-faking tilt-shift look — scenes that resemble tiny models.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "tilt-shift photograph",
      composition: "high vantage looking down on a scene, narrow band of sharp focus across the subject",
      lighting: "bright saturated daylight",
      camera: "tilt-shift lens, extremely shallow focal plane, strong top-and-bottom blur",
      color: "punchy saturated color that enhances the toy-model illusion",
      mood: "playful, miniature, whimsical",
      detail: "tiny crisp detail in the focus band, smooth blur elsewhere",
    },
    avoid: ["uniform sharpness", "flat lighting", "muted color", "watermark"],
  },
  {
    id: "film-35mm",
    category: "photography",
    title: "35mm film",
    description: "Analog 35mm film look with grain and natural color. Nostalgic, candid, editorial.",
    recommended: { size: "1536x1024", quality: "high", format: "jpeg" },
    dims: {
      medium: "35mm analog film photograph",
      composition: "candid, naturalistic framing",
      lighting: "available natural light with soft highlight roll-off",
      camera: "shot on 35mm film with a 50mm lens, gentle grain, slight halation",
      color: "warm filmic color with soft contrast, classic film-stock palette",
      mood: "nostalgic, authentic, timeless",
      detail: "fine film grain, organic texture, natural imperfections",
    },
    avoid: ["clinical digital sharpness", "HDR look", "plastic skin", "watermark"],
  },
  {
    id: "double-exposure",
    category: "photography",
    title: "Double exposure",
    description: "Artistic blend of two images (often a silhouette filled with a scene). Posters, covers.",
    recommended: { size: "1024x1536", quality: "high", format: "jpeg" },
    dims: {
      medium: "double-exposure photograph",
      composition: "a bold silhouette whose interior is filled with a second blended scene",
      lighting: "high-key contrast between the silhouette and a clean background",
      color: "restrained palette so the two layers read clearly",
      mood: "poetic, evocative, artful",
      detail: "seamless blend of the two exposures, clear silhouette edge, balanced overlay",
    },
    avoid: ["muddy overlap", "busy background", "low contrast", "watermark"],
  },
];
