import type { Preset } from "../types.js";

export const render3d: Preset[] = [
  {
    id: "isometric-3d",
    category: "render3d",
    title: "Isometric 3D scene",
    description: "Cute isometric 3D diorama. Tech illustrations, app concepts, explainer scenes.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "isometric 3D render with clean PBR materials and orthographic projection",
      composition: "true 2:1 isometric angle, no vanishing-point convergence, a single tidy diorama resting on a small rounded base, centered with even margins",
      setting: "uncluttered solid or soft vertical-gradient background that lets the diorama read clearly",
      lighting: "soft global illumination with a key from upper-left, gentle ambient occlusion in the crevices, and one grounded soft contact shadow",
      color: "bright cohesive palette, two or three pastel-to-saturated accents balanced against neutral surfaces",
      mood: "clean, playful, modern tech-explainer",
      detail: "smooth rounded geometry with beveled edges, soft-touch matte plastic surfacing, crisp silhouettes, miniature-diorama charm",
    },
    avoid: ["perspective convergence", "cluttered overlapping props", "speech bubbles or chat bubbles", "floating UI icons and badge clutter", "any text, labels or lettering", "gritty realism", "harsh cast shadows", "watermark"],
  },
  {
    id: "clay-render",
    category: "render3d",
    title: "Clay / soft 3D render",
    description: "Matte clay-material 3D with rounded forms. Trendy 3D mascots, hero objects.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "soft matte clay-material 3D render with subsurface scattering in the highlights",
      composition: "a single hero object or character, centered, built from friendly rounded forms with chunky proportions",
      setting: "soft solid-color or gentle radial-gradient backdrop in a complementary tone",
      lighting: "broad soft area-light key with a fill bounce, smooth wraparound shadows, and gentle ambient occlusion where forms meet",
      color: "soft muted pastel palette, fully matte non-reflective surfaces with a slight velvety roll-off",
      mood: "friendly, tactile, contemporary",
      detail: "smooth subdivided geometry, fingerprint-free clay surface with faint subsurface translucency, soft grounded contact shadow",
    },
    avoid: ["sharp gritty detail", "glossy or specular reflections", "complex backgrounds", "hard-edged shadows", "watermark"],
  },
  {
    id: "low-poly",
    category: "render3d",
    title: "Low-poly 3D",
    description: "Faceted low-poly geometry with flat shading. Games, stylized scenes, icons.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "stylized low-poly 3D render with flat-shaded faceted geometry",
      composition: "a clear faceted subject in balanced three-quarter framing reading as a tidy game asset",
      setting: "simple flat or low-poly gradient backdrop that keeps the silhouette legible",
      lighting: "single directional key with hard flat-shaded falloff so each polygon facet reads as a distinct tonal plane, minimal soft fill",
      color: "vibrant flat per-face palette with crisp value steps between adjacent facets",
      mood: "geometric, stylized, clean",
      detail: "visible triangulated facets, faceted flat shading with no smoothing groups, sharp polygon edges and clean vertices",
    },
    avoid: ["smooth high-poly or subdivided surfaces", "photorealism", "fine texture or normal-map detail", "gradient shading across faces", "watermark"],
  },
  {
    id: "product-3d-render",
    category: "render3d",
    title: "Product 3D render (CGI)",
    description: "Photoreal CGI product render with studio reflections. Configurators, packshots.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "photoreal CGI product render with physically-based materials",
      composition: "hero three-quarter angle from a 50mm lens, product centered on a seamless reflective floor with a clean horizon sweep",
      setting: "clean studio cyclorama with a soft gradient backdrop and a subtle floor reflection",
      lighting: "HDRI studio environment with large softbox key reflections, a rim light separating the edge, and crisp rectangular highlight strips on the gloss",
      color: "physically accurate materials, calibrated true color, controlled contrast with clean specular roll-off",
      mood: "premium, clinical, commercial",
      detail: "PBR surfacing with correct roughness and metalness, accurate reflections and refractions, ray-traced soft shadows and contact occlusion, razor-sharp edges",
    },
    avoid: ["rough or unfinished surfaces", "render noise or fireflies", "flat even lighting", "blown-out highlights", "watermark"],
  },
  {
    id: "glass-3d",
    category: "render3d",
    title: "Glassmorphism 3D",
    description: "Frosted translucent glass shapes with refraction. Modern abstract hero objects.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "abstract 3D render of translucent frosted-glass forms with physically-based refraction",
      composition: "an elegant arrangement of overlapping glass shapes, centered, floating with a sense of weightlessness and layered depth",
      setting: "soft vertical-gradient backdrop that glows through the glass",
      lighting: "soft studio light transmitted through the forms, casting colorful refracted caustics and a faint bloom",
      color: "iridescent pastel gradients bending and separating as they refract through the frosted glass",
      mood: "sleek, futuristic, premium",
      detail: "accurate refraction with index-of-refraction bending, frosted-surface translucency and soft internal blur, subtle chromatic dispersion at the edges, smooth polished surfaces",
    },
    avoid: ["opaque or solid fills", "harsh hard edges", "busy background", "muddy or grey refractions", "watermark"],
  },
  {
    id: "voxel",
    category: "render3d",
    title: "Voxel art",
    description: "Cute cubic voxel scene (MagicaVoxel look). Game assets, playful dioramas.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "voxel 3D render built from uniform cubes in a MagicaVoxel style",
      composition: "an isometric orthographic voxel diorama, a single tidy scene on a compact cubic base, centered",
      setting: "plain solid background so the blocky silhouette stays crisp",
      lighting: "soft ambient occlusion darkening the seams between cubes with one gentle directional key for grounded soft shadows",
      color: "bright cohesive palette with flat per-voxel colors and clean value steps",
      mood: "playful, retro-game, charming",
      detail: "clean cubic voxel blocks at a single consistent grid scale, sharp aliased cube edges, no sub-voxel detail",
    },
    avoid: ["smooth or rounded surfaces", "photorealism", "perspective convergence", "inconsistent voxel sizes", "watermark"],
  },
];
