import type { Preset } from "../types.js";

export const render3d: Preset[] = [
  {
    id: "isometric-3d",
    category: "render3d",
    title: "Isometric 3D scene",
    description: "Cute isometric 3D diorama. Tech illustrations, app concepts, explainer scenes.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "isometric 3D render",
      composition: "true isometric angle, single tidy diorama floating or on a small base, centered",
      setting: "clean solid or soft-gradient background",
      lighting: "soft global illumination with gentle ambient occlusion and a soft shadow",
      color: "bright cohesive palette, pastel or vibrant",
      mood: "clean, playful, modern tech",
      detail: "smooth rounded geometry, clean materials, crisp edges, miniature-diorama charm",
    },
    avoid: ["perspective distortion", "cluttered scene", "gritty realism", "watermark"],
  },
  {
    id: "clay-render",
    category: "render3d",
    title: "Clay / soft 3D render",
    description: "Matte clay-material 3D with rounded forms. Trendy 3D mascots, hero objects.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "soft matte clay-material 3D render",
      composition: "single hero object or character, centered, friendly rounded forms",
      setting: "soft solid-color or gradient backdrop",
      lighting: "soft studio lighting with smooth shadows and gentle ambient occlusion",
      color: "soft pastel palette, matte non-reflective materials",
      mood: "friendly, tactile, contemporary",
      detail: "smooth subdivided geometry, clay-like matte surface, soft realistic shadows",
    },
    avoid: ["sharp gritty detail", "glossy reflections", "complex backgrounds", "watermark"],
  },
  {
    id: "low-poly",
    category: "render3d",
    title: "Low-poly 3D",
    description: "Faceted low-poly geometry with flat shading. Games, stylized scenes, icons.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "stylized low-poly 3D render",
      composition: "clear faceted subject, balanced framing",
      lighting: "simple directional lighting emphasizing flat polygon facets",
      color: "vibrant flat-shaded color palette",
      mood: "geometric, stylized, clean",
      detail: "visible triangulated facets, flat per-face shading, crisp polygon edges",
    },
    avoid: ["smooth high-poly surfaces", "photorealism", "fine texture", "watermark"],
  },
  {
    id: "product-3d-render",
    category: "render3d",
    title: "Product 3D render (CGI)",
    description: "Photoreal CGI product render with studio reflections. Configurators, packshots.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "photorealistic 3D product render (CGI)",
      composition: "hero three-quarter angle, product centered on a reflective floor",
      setting: "clean studio environment with gradient backdrop and subtle reflection",
      lighting: "large softbox reflections and HDRI studio lighting, crisp highlight strips",
      color: "accurate materials, true color, controlled contrast",
      mood: "premium, clinical, commercial",
      detail: "physically-based materials, accurate reflections and refractions, ray-traced shadows, ultra-sharp",
    },
    avoid: ["rough surfaces", "noisy render", "flat lighting", "watermark"],
  },
  {
    id: "glass-3d",
    category: "render3d",
    title: "Glassmorphism 3D",
    description: "Frosted translucent glass shapes with refraction. Modern abstract hero objects.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "abstract 3D render of translucent frosted-glass forms",
      composition: "elegant arrangement of glass shapes, centered, sense of weightlessness",
      setting: "soft gradient backdrop",
      lighting: "soft studio light with colorful refractions and caustics",
      color: "iridescent pastel gradients refracted through glass",
      mood: "sleek, futuristic, premium",
      detail: "realistic refraction, frosted translucency, subtle chromatic dispersion, smooth surfaces",
    },
    avoid: ["opaque materials", "harsh edges", "busy background", "watermark"],
  },
  {
    id: "voxel",
    category: "render3d",
    title: "Voxel art",
    description: "Cute cubic voxel scene (MagicaVoxel look). Game assets, playful dioramas.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "voxel 3D render made of small cubes",
      composition: "isometric voxel diorama, single tidy scene",
      lighting: "soft ambient lighting with gentle shadows between cubes",
      color: "bright cohesive palette",
      mood: "playful, retro-game, charming",
      detail: "clean cubic voxel blocks, consistent voxel scale, crisp edges",
    },
    avoid: ["smooth surfaces", "photorealism", "perspective distortion", "watermark"],
  },
];
