import type { Preset } from "../types.js";

export const specialized: Preset[] = [
  {
    id: "pixel-art",
    category: "specialized",
    title: "Pixel art",
    description: "Crisp retro pixel art with a limited palette. Game sprites, icons, retro scenes.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "hand-placed pixel-art sprite rendered at a low native resolution and scaled up with nearest-neighbor, every pixel snapped to a square grid",
      composition: "single readable subject framed with clear silhouette and room around it, sitting on a flat simple or transparent background",
      color: "tight indexed palette of roughly 8 to 16 colors, shading built from ordered dithering and hand-stepped ramps rather than smooth blends",
      mood: "nostalgic 8-bit and 16-bit game art, console-era charm",
      detail: "crisp uniform pixels on a consistent grid, hard aliased edges, deliberate single-pixel outlines, no anti-aliasing, no blur, no sub-pixel softening",
    },
    avoid: ["smooth gradients", "anti-aliasing", "blurred or feathered edges", "uneven pixel sizes", "mixed pixel scales", "photorealism", "watermark"],
  },
  {
    id: "blueprint",
    category: "specialized",
    title: "Technical blueprint",
    description: "White-line schematic on blue ground. Technical concepts, patents, engineering vibe.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "engineering blueprint reproduced as a cyanotype-style technical drawing",
      composition: "orthographic projection with front, top and side views laid out squarely, leader and callout lines pointing to labelled parts, a ruled title block in one corner",
      color: "thin white and pale-cyan lines on a deep blueprint-blue ground, no fills, line color reading as exposed paper",
      mood: "precise, engineered, drafted by hand at a drawing board",
      detail: "consistent crisp line weights with heavier outlines and lighter hidden and center lines, dimension lines with arrowheads and measurement ticks, a faint underlying drafting grid",
    },
    avoid: ["photorealism", "solid color fills", "painterly shading", "perspective foreshortening", "watermark"],
  },
  {
    id: "coloring-page",
    category: "specialized",
    title: "Coloring-book page",
    description: "Clean black-outline line drawing for coloring. Kids activities, printables.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "black-and-white coloring-book line drawing built from clean closed contours",
      composition: "one clear friendly subject filling the page with generous open white regions sized for crayons and markers, simple uncluttered background",
      color: "pure solid-black outlines on plain white, zero fill, zero gray, every shape left empty to color in",
      mood: "playful, simple, welcoming to young children",
      detail: "smooth even-weight outlines of uniform thickness, every region fully enclosed with no broken or open gaps, rounded friendly forms, no shading or hatching",
    },
    avoid: ["shading", "gray tones", "any color fill", "cross-hatching or stippling", "broken or open outlines", "thin wispy lines", "photorealism", "watermark"],
  },
  {
    id: "infographic-element",
    category: "specialized",
    title: "Infographic element",
    description: "Clean iconographic spot graphic for slides, infographics, explainers.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "clean flat-design infographic spot illustration",
      composition: "single clear concept reduced to simple symbolic forms, every element snapped to a tidy grid with equal gutters, consistent padding and shared baselines so nothing drifts",
      color: "flat palette of one accent color plus a neutral, that single accent reused across every element with no arbitrary extra hues, strong figure-to-ground contrast",
      mood: "clear, informative, modern",
      detail: "uniform iconographic shapes drawn at matching scale and stroke weight, each icon optically centered inside its container or circle with equal margins, elements aligned and evenly spaced, instantly legible at small size",
    },
    avoid: ["photorealism", "clutter", "tiny unreadable detail", "more than one accent color", "mismatched icon sizes or stroke weights", "misaligned or drifting elements", "icons overflowing or off-center in their circles", "uneven spacing", "watermark"],
  },
  {
    id: "tattoo-flash",
    category: "specialized",
    title: "Tattoo flash",
    description: "Bold traditional tattoo flash design. Body art concepts, merch, bold graphics.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "American-traditional tattoo flash design in the Sailor Jerry lineage",
      composition: "bold centered motif with a strong clean silhouette and a little breathing room, drawn to read clearly once tattooed on skin",
      color: "heavy black outlines filled with a limited classic-traditional palette of brick red, golden yellow, leaf green and a touch of blue, flat solid color",
      mood: "bold, iconic, old-school Americana",
      detail: "thick confident even outlines, solid black-fill shading with whip-shaded gradients only where traditional, deliberate open negative space, the tight polished composition of a hand-painted flash sheet",
    },
    avoid: ["fine photorealistic detail", "soft airbrushed gradients", "pastel or washed-out palette", "thin sketchy linework", "weak generic design", "text or lettering", "watermark"],
  },
  {
    id: "cyberpunk",
    category: "specialized",
    title: "Cyberpunk neon",
    description: "Moody neon-lit cyberpunk scene. Sci-fi key art, atmospheric backgrounds.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "cinematic cyberpunk scene with the feel of anamorphic key art",
      composition: "dense futuristic framing with strong foreground-to-background depth, layered planes and clean reflections leading the eye",
      setting: "rain-slick neon-drenched future cityscape, stacked holographic signage and glowing storefronts receding into night",
      lighting: "vivid neon as the key light, controlled glow and gentle atmospheric haze, wet specular highlights on slick surfaces",
      color: "electric magenta and cyan neon set against deep near-black shadow, high contrast with rich saturation",
      mood: "moody, futuristic, cinematic",
      detail: "the main subject held crisp and sharp, clean neon bokeh in the background, restrained haze that adds depth without veiling the frame, believable high-tech surface detail",
    },
    avoid: ["flat daylight", "clean minimalism", "muted desaturated colors", "heavy film grain", "excessive sensor noise", "blurry or muddy subject", "smeared neon", "watermark"],
  },
  {
    id: "retro-80s",
    category: "specialized",
    title: "Retro 80s / synthwave",
    description: "Nostalgic synthwave aesthetic with grids and sunset gradients. Music, retro branding.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "retro 1980s synthwave illustration in the Outrun aesthetic",
      composition: "iconic synthwave layout, a glowing neon wireframe grid receding to a low horizon where a banded gradient sun sets",
      color: "hot-pink, magenta, purple and cyan gradients with polished chrome accents",
      lighting: "glowing neon edges and a smooth sunset gradient wash across the sky",
      mood: "nostalgic, electric, dreamy",
      detail: "a clean one-point-perspective floor grid, abstract chrome geometric shapes (purely abstract, no real words or letters), subtle scanlines and fine grain, glowing neon outlines",
    },
    avoid: ["modern minimalism", "muted palette", "photorealism", "text or lettering", "garbled words", "real readable typography", "watermark"],
  },
  {
    id: "minimalist",
    category: "specialized",
    title: "Minimalist poster",
    description: "Ultra-clean minimalist composition with bold negative space. Posters, brand art.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "minimalist graphic poster in the Swiss-design tradition",
      composition: "one bold simple subject anchored off-center, dominant negative space carrying most of the frame, confident asymmetric balance with intentional margins",
      color: "restrained palette of two or three flat colors, one doing the work as an accent",
      mood: "calm, sophisticated, modern",
      detail: "clean geometric simplicity, precise alignment and crisp edges, generous breathing room, every element earning its place with nothing superfluous",
    },
    avoid: ["clutter", "busy detail", "gradients", "decorative noise", "filled-in negative space", "photorealism", "watermark"],
  },
  {
    id: "trading-card",
    category: "specialized",
    title: "Trading-card asset",
    description: "Game/collectible trading-card layout: framed character art with border and panels.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "a collectible trading-card design with a clean printed layout",
      composition: "central character or creature artwork seated in a portrait art window, a title bar across the top and a tidy stats panel along the bottom, every panel squared to a shared margin and evenly spaced",
      setting: "framed decorative card border with simple corner motifs containing the art",
      lighting: "dramatic illustrative lighting on the central art, flat and even on the frame and panels",
      color: "rich themed palette for the art with restrained metallic accents on the frame",
      mood: "epic, collectible, polished",
      detail: "clean uncluttered layout with aligned panels and consistent borders, a tastefully restrained frame that frames rather than competes, a clearly legible title and neat stat labels, moderate balanced ornamentation",
    },
    avoid: ["full-bleed art with no frame", "cluttered busy layout", "excessive ornamentation", "misaligned or crooked panels", "art spilling past the frame", "gibberish text", "watermark"],
  },
  {
    id: "character-turnaround",
    category: "specialized",
    title: "Character turnaround sheet",
    description: "Model sheet showing one character from multiple angles for consistent design.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "a character turnaround model sheet of the kind used in animation and game production",
      composition: "the same single character repeated in a row from front, three-quarter, side and back views, standing in a neutral A-pose at identical scale and aligned to shared horizontal guide lines",
      setting: "plain neutral background with a subtle ground baseline, no scenery",
      lighting: "flat even reference lighting, no dramatic shadows or rim light, color reading true in every view",
      color: "exactly the same character colors and material values carried across every angle",
      mood: "clean, technical, reference-quality",
      detail: "one identical character design in each pose with matching proportions, costume details and silhouette from view to view, no pose or outfit variation",
    },
    avoid: ["different character per view", "inconsistent proportions between views", "dramatic shadows or rim lighting", "busy background", "scenery or props", "watermark"],
  },
];
