import type { Preset } from "../types.js";

export const specialized: Preset[] = [
  {
    id: "pixel-art",
    category: "specialized",
    title: "Pixel art",
    description: "Crisp retro pixel art with a limited palette. Game sprites, icons, retro scenes.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "retro pixel-art sprite",
      composition: "clear readable subject on a simple or transparent background",
      color: "limited retro palette, deliberate dithering for shading",
      mood: "nostalgic, 8-bit/16-bit game",
      detail: "crisp aligned pixels, hard edges, no anti-aliasing or blur, consistent pixel grid",
    },
    avoid: ["smooth gradients", "anti-aliasing", "blur", "photorealism", "watermark"],
  },
  {
    id: "blueprint",
    category: "specialized",
    title: "Technical blueprint",
    description: "White-line schematic on blue ground. Technical concepts, patents, engineering vibe.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "technical blueprint schematic drawing",
      composition: "orthographic technical drawing with measured precision, callout lines and grid",
      color: "white and light-cyan lines on deep blueprint-blue background",
      mood: "precise, engineered, technical",
      detail: "fine consistent line weights, dimension lines, annotations, drafting grid",
    },
    avoid: ["photorealism", "color fills", "painterly shading", "watermark"],
  },
  {
    id: "coloring-page",
    category: "specialized",
    title: "Coloring-book page",
    description: "Clean black-outline line drawing for coloring. Kids activities, printables.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "black-and-white coloring-book line drawing",
      composition: "clear friendly subject with bold closed outlines, plenty of open areas to color",
      color: "pure black outlines on a white background, no fill or shading",
      mood: "playful, simple, kid-friendly",
      detail: "smooth bold even outlines, fully enclosed regions, no gray shading",
    },
    avoid: ["shading", "gray tones", "color", "fine cross-hatching", "photorealism", "watermark"],
  },
  {
    id: "infographic-element",
    category: "specialized",
    title: "Infographic element",
    description: "Clean iconographic spot graphic for slides, infographics, explainers.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    dims: {
      medium: "clean infographic spot illustration",
      composition: "single clear concept, simplified and symbolic, elements aligned on a tidy grid with consistent even spacing and balanced padding",
      color: "flat brand-friendly palette using ONE accent color consistently across all elements (do not mix arbitrary colors), clear contrast",
      mood: "clear, informative, modern",
      detail: "simple consistent iconographic shapes of equal size, each icon centered within its container or circle, even line weight, neatly aligned and evenly spaced, instantly legible",
    },
    avoid: ["photorealism", "clutter", "tiny unreadable detail", "inconsistent colors", "misaligned elements", "icons overflowing their circles", "uneven spacing", "watermark"],
  },
  {
    id: "tattoo-flash",
    category: "specialized",
    title: "Tattoo flash",
    description: "Bold traditional tattoo flash design. Body art concepts, merch, bold graphics.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "traditional tattoo flash design",
      composition: "bold centered motif, clean silhouette, designed to read on skin",
      color: "bold black linework with limited classic-tattoo color accents",
      mood: "bold, iconic, old-school",
      detail: "thick confident outlines, solid black shading, clean negative space, a striking iconic well-composed design with the polish of a professional flash sheet",
    },
    avoid: ["fine photorealistic detail", "soft gradients", "pastel palette", "weak generic design", "watermark"],
  },
  {
    id: "cyberpunk",
    category: "specialized",
    title: "Cyberpunk neon",
    description: "Moody neon-lit cyberpunk scene. Sci-fi key art, atmospheric backgrounds.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "cinematic cyberpunk scene",
      composition: "dense futuristic city or character framing with strong depth and reflections",
      setting: "rain-slick neon-drenched future cityscape with holograms and signage",
      lighting: "vivid neon glow, light atmospheric haze, wet reflective highlights",
      color: "electric magenta-and-cyan neon against deep shadow, high contrast",
      mood: "moody, futuristic, cinematic",
      detail: "crisp sharp detail on the main subject, clean neon bokeh, moderate atmospheric haze, high-tech detail",
    },
    avoid: ["flat daylight", "clean minimalism", "muted colors", "heavy film grain", "excessive noise", "blurry muddy details", "watermark"],
  },
  {
    id: "retro-80s",
    category: "specialized",
    title: "Retro 80s / synthwave",
    description: "Nostalgic synthwave aesthetic with grids and sunset gradients. Music, retro branding.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "retro 1980s synthwave illustration",
      composition: "iconic synthwave layout, neon horizon grid receding to a setting sun",
      color: "hot-pink, purple and cyan gradients, chrome accents",
      lighting: "glowing neon and sunset gradient light",
      mood: "nostalgic, electric, dreamy",
      detail: "perspective grid, abstract chrome geometric shapes (no actual words or letters), scanline and grain texture, glowing outlines",
    },
    avoid: ["modern minimalism", "muted palette", "photorealism", "text or lettering", "garbled words", "watermark"],
  },
  {
    id: "minimalist",
    category: "specialized",
    title: "Minimalist poster",
    description: "Ultra-clean minimalist composition with bold negative space. Posters, brand art.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "minimalist graphic poster",
      composition: "one bold simple subject, dominant negative space, strong asymmetric balance",
      color: "restrained palette of two or three flat colors",
      mood: "calm, sophisticated, modern",
      detail: "clean geometric simplicity, perfect alignment, nothing superfluous",
    },
    avoid: ["clutter", "busy detail", "gradients", "photorealism", "watermark"],
  },
  {
    id: "trading-card",
    category: "specialized",
    title: "Trading-card asset",
    description: "Game/collectible trading-card layout: framed character art with border and panels.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "a collectible trading-card design",
      composition: "central character/creature artwork inside a clean, well-aligned card frame, a title bar at top and a tidy stats panel at the bottom — panels neatly aligned and evenly spaced",
      setting: "decorative card border with corner motifs",
      lighting: "dramatic illustrative lighting on the central art",
      color: "rich themed palette with metallic frame accents",
      mood: "epic, collectible, polished",
      detail: "clean uncluttered layout with neatly aligned panels, a tastefully restrained (not overly busy) frame, well-centered title and stat labels, moderate ornamentation",
    },
    avoid: ["full-bleed art with no frame", "cluttered busy layout", "excessive ornamentation", "misaligned panels", "gibberish text", "watermark"],
  },
  {
    id: "character-turnaround",
    category: "specialized",
    title: "Character turnaround sheet",
    description: "Model sheet showing one character from multiple angles for consistent design.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "a character turnaround model sheet",
      composition: "the same character shown in a row from multiple angles (front, three-quarter, side, back), consistent scale on a neutral grid",
      setting: "plain neutral background with a subtle baseline",
      lighting: "flat even reference lighting with no dramatic shadows",
      color: "consistent character colors across every view",
      mood: "clean, technical, reference-quality",
      detail: "identical character design in every pose, consistent proportions, clear silhouette",
    },
    avoid: ["different character per view", "dramatic shadows", "busy background", "watermark"],
  },
];
