import type { Preset } from "../types.js";

// Web / app dev & "vibe coding" assets. Most default to a transparent background so they drop
// straight onto a page/UI and composite cleanly. (On the subscription backend, transparency is
// produced by rendering on a chroma field and keying it out locally — best on clean-edged subjects;
// glossy 3D may need a touch of edge cleanup.)
export const webdev: Preset[] = [
  {
    id: "hero-3d",
    category: "webdev",
    title: "Hero 3D element (transparent)",
    description: "A floating abstract 3D form for a landing-page hero. Transparent — drops onto any section.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a contemporary abstract 3D hero element rendered like a clean studio product shot, smooth subdivision-surface modeling with soft bevels",
      composition: "one floating sculptural 3D form (a fluid liquid form, a soft torus knot, or a calm cluster of rounded geometric solids) as an ABSTRACT evocation of the subject — never a literal object, interface or icon — centered with generous breathing room and a gentle three-quarter hero angle, fully isolated on its own",
      lighting: "soft diffuse studio HDRI light with a large key and a subtle fill, gentle ambient occlusion in the crevices and a soft specular sheen rolling across the surface, no cast ground shadow and no visible floor",
      color: "a single refined hue with a restrained tonal gradient into a close neighbour, balanced against a neutral — take the hue from the brand or subject when one is given, otherwise choose ONE of deep teal, warm terracotta, forest green, or graphite with a brass accent; never violet, purple or a holographic rainbow; a material that feels real: frosted glass, brushed metal, matte ceramic or smooth clay",
      mood: "premium, contemporary, polished SaaS landing-page aesthetic — restrained, not flashy",
      detail: "clean smooth surface with crisp silhouette edges, gentle reflections and a faint rim of light, fully isolated with no halos, fringing or green color spill around the edges",
    },
    avoid: ["background scenery or environment", "cast ground shadow or reflective floor", "busy or overcrowded composition", "literal browser windows, app panels, charts or UI icons", "violet or purple hues", "holographic or iridescent rainbow finish", "green color spill on edges", "halos or fringing", "muddy or contradictory gradients", "watermark"],
  },
  {
    id: "icon-3d",
    category: "webdev",
    title: "3D icon (transparent)",
    description: "A glossy rounded 3D icon object — the trendy dashboard/feature icon look. Transparent.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a glossy rounded 3D icon object in the trendy dashboard / feature-tile style, soft-bevelled and chunky",
      composition: "one single 3D icon object centered with even padding, posed at a slight hero three-quarter angle so it reads with depth, fully isolated on its own",
      lighting: "soft diffuse studio light with a broad key, gentle ambient occlusion where forms meet and a clean specular highlight on top, no background or contact shadow",
      color: "bright modern UI palette with a smooth two-tone gradient face, finished as either a wet-glossy plastic or a soft matte-clay material",
      mood: "playful, premium, modern product UI",
      detail: "smooth rounded geometry with consistent corner radii, clean physically-based materials, crisp silhouette edges, no halos, fringing or green spill",
    },
    avoid: ["background or environment", "cast or contact shadow on a surface", "gritty or photoreal realism", "green color spill", "halos or fringing", "embedded text or labels", "watermark"],
  },
  {
    id: "glyph-icon",
    category: "webdev",
    title: "UI glyph icon (transparent)",
    description: "A clean single-weight line/glyph icon for UI. Monochrome, transparent, scalable.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a clean UI glyph icon drawn in a single-weight outline style, like a modern open-source icon set (Lucide / Feather / Heroicons)",
      composition: "one simple centered pictogram on a tidy pixel grid with generous even optical padding and a consistent safe margin, optically balanced within its bounding box",
      color: "flat monochrome in a single solid stroke color, no fill and no background",
      mood: "minimal, modern, functional system UI",
      detail: "uniform stroke weight throughout, rounded line caps and rounded corner joins, evenly distributed negative space, crisp scalable vector-like edges that stay legible at 16-24px",
    },
    avoid: ["photorealism", "gradients or shading", "drop shadows", "solid fills", "fussy fine detail", "embedded text or labels", "watermark"],
  },
  {
    id: "spot-illustration",
    category: "webdev",
    title: "Spot illustration (transparent)",
    description: "Modern feature / empty-state illustration for web & apps. Transparent.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a modern flat-with-gradient spot illustration for a web feature card or empty state, in the polished premium product-illustration style (tasteful, not cliché corporate-memphis)",
      composition: "one clear friendly conceptual scene or hero object built from simple geometric shapes, balanced around a strong focal point with generous negative space, fully isolated",
      color: "cohesive limited palette of three or four hues with smooth soft gradient fills, gentle tonal shading and one confident accent color carrying the eye",
      mood: "friendly, modern, product-marketing",
      detail: "clean rounded shapes with subtle depth and layered overlap, soft inner shadows for dimension, a refined contemporary tech-illustration finish with crisp clean edges",
    },
    avoid: ["photorealism", "harsh black outlines", "cheap clip-art look", "busy clutter or overcrowding", "background or scene fill", "muddy clashing palette", "watermark"],
  },
  {
    id: "abstract-blob",
    category: "webdev",
    title: "Decorative blob (transparent)",
    description: "A soft organic gradient blob/shape for section backgrounds and accents. Transparent.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a decorative abstract gradient blob, the kind used as a soft section accent or backdrop flourish behind UI",
      composition: "one single smooth organic blob with soft rounded lobes and gentle asymmetry, centered with even margin, fully isolated",
      color: "smooth modern multi-stop gradient in brand-friendly hues flowing diagonally across the shape, soft and tasteful with mellow contrast",
      mood: "calm, contemporary, decorative",
      detail: "clean vector-like silhouette with soft feathered edges, a faint fine grain to keep the gradient from banding, no hard outline and no inner detail",
    },
    avoid: ["hard outline or stroke", "busy inner detail", "photorealism", "background fill", "embedded text", "visible banding", "watermark"],
  },
  {
    id: "mesh-gradient",
    category: "webdev",
    title: "Mesh / aurora gradient background",
    description: "Full-bleed modern mesh-gradient hero background (opaque). For landing sections.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "a modern full-bleed mesh / aurora gradient background, the soft blurred multi-point-gradient look popular on landing hero sections",
      composition: "a smooth multi-color mesh gradient with soft blooming color pools filling the entire frame edge to edge, no subject, leaving one calmer lower-contrast zone with room for overlaid headline text",
      color: "soft blended contemporary hues (violet, electric blue, teal and warm pink) melting into one another with long smooth transitions and no hard color boundaries",
      mood: "premium, calm, contemporary",
      detail: "seamless buttery gradient blend with a subtle fine film grain layered over it to dither away any banding, even and flat with no vignette",
    },
    avoid: ["visible color banding or stepping", "harsh edges or seams", "any subject, object or shape", "embedded text", "heavy vignette", "watermark"],
  },
  {
    id: "device-mockup",
    category: "webdev",
    title: "Device mockup (transparent)",
    description: "A floating phone/laptop showing an app screen, isolated. For showcasing UIs.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a clean device mockup presenting an app, like a modern bezel-less smartphone product render",
      composition: "one current-generation smartphone with slim uniform bezels and rounded corners, floating at a slight three-quarter angle to show a little side depth, displaying a polished app screen, fully isolated",
      lighting: "soft diffuse studio light with a gentle highlight gliding down the glass and a subtle emissive screen glow, no background or ground shadow",
      color: "neutral matte device body (graphite, silver or off-white) framing a vibrant realistic app UI on the display",
      mood: "premium, product-showcase, modern",
      detail: "crisp clean device edges, a believable on-screen UI with a clear status bar, real layout hierarchy, cards and a nav bar, fully isolated with no halos, fringing or green spill",
    },
    avoid: ["background scenery or environment", "cast ground shadow or reflective floor", "gibberish or scrambled on-screen text", "green color spill", "halos or fringing", "outdated thick-bezel phone", "watermark"],
  },
  {
    id: "avatar",
    category: "webdev",
    title: "Avatar illustration (transparent)",
    description: "A stylized profile avatar for users/testimonials. Transparent, consistent style.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a stylized character avatar illustration in a modern flat-vector profile style, suited to a user chip or testimonial card",
      composition: "a friendly head-and-shoulders portrait centered and framed with even headroom, simple and clearly readable as a small circular crop, fully isolated",
      color: "modern flat palette with soft cel-style shading, gentle warmth in the skin tones and one confident accent on hair or clothing",
      mood: "friendly, approachable, contemporary",
      detail: "clean vector-like rendering with rounded forms, distinctive features and a repeatable style language that stays consistent across a set, crisp clean edges",
    },
    avoid: ["photorealism", "busy or detailed background", "harsh black outlines", "background fill", "halos or fringing", "off-center crop", "watermark"],
  },
  {
    id: "mascot",
    category: "webdev",
    title: "Brand mascot (transparent)",
    description: "A single friendly brand mascot character for a product/site. Transparent.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a friendly brand mascot character in a clean modern flat-vector style, designed to scale from app icon to hero",
      composition: "one single full-body mascot in a clear lively yet readable pose with a strong recognizable silhouette, centered with even margin and fully isolated",
      color: "bold cohesive brand palette of a few hues with simple clean cel shading and a touch of soft gradient for volume",
      mood: "friendly, memorable, brandable",
      detail: "appealing modern character design with an expressive face, simple rounded shapes, consistent proportions and a repeatable model-sheet style, crisp clean edges with no halos, fringing or green spill",
    },
    avoid: ["background scenery or props", "photorealism", "inconsistent or off-model design", "green color spill", "halos or fringing", "muddy palette", "watermark"],
  },
  {
    id: "wireframe",
    category: "webdev",
    title: "Lo-fi UI wireframe",
    description: "A greyscale low-fidelity wireframe of an app/web screen. For planning & specs.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "a low-fidelity UI wireframe mockup, the schematic skeleton-screen style used in early product design",
      composition: "a clean greyscale wireframe of an app or web screen with clearly blocked-out regions — a top header bar, a content area of stacked cards or a list, and a bottom or side nav — all snapped to a consistent column grid with even gutters and aligned margins",
      color: "strictly greyscale: light-grey filled boxes and placeholder blocks, mid-grey outlines and divider lines on a plain white background",
      mood: "schematic, structural, planning-stage",
      detail: "plain grey rectangles for containers, short horizontal grey bars standing in for text lines, an 'X' or simple outline shape for image placeholders, basic line icons, tidy consistent spacing, no real copy and no color",
    },
    avoid: ["full color or accent colors", "realistic high-fidelity finished UI", "photorealism", "real legible body text or paragraphs", "drop shadows or depth effects", "watermark"],
  },
];
