import type { Preset } from "../types.js";

// Web / app dev & "vibe coding" assets. Most default to a transparent background so they drop
// straight onto a page/UI and composite cleanly. (On the subscription backend, transparency is
// produced by rendering on a chroma field and keying it out locally — best on clean-edged subjects;
// glossy 3D may need a touch of edge cleanup.)
export const webdev: Preset[] = [
  {
    id: "hero-3d",
    category: "webdev",
    title: "Hero 3D element (transparent)",
    description: "A floating abstract 3D form for a landing-page hero. Transparent — drops onto any section.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a modern abstract 3D hero element, clean studio render",
      composition: "a single floating abstract 3D form (fluid blob, twisted ribbon, torus or soft geometric cluster), centered with breathing room, isolated",
      lighting: "soft studio lighting with a gentle gradient sheen and subtle ambient occlusion, no cast ground shadow",
      color: "vibrant modern gradient finish (violet-to-blue, coral-to-pink, or teal), glossy or soft-matte",
      mood: "premium, contemporary, SaaS landing-page",
      detail: "smooth high-quality 3D surface, crisp clean edges, subtle reflections, fully isolated with no halos or fringing",
    },
    avoid: ["background scenery", "cast ground shadow", "busy composition", "green color spill", "halos or fringing", "watermark"],
  },
  {
    id: "icon-3d",
    category: "webdev",
    title: "3D icon (transparent)",
    description: "A glossy rounded 3D icon object — the trendy dashboard/feature icon look. Transparent.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a glossy rounded 3D icon object",
      composition: "a single 3D icon object centered, slight hero three-quarter angle, isolated",
      lighting: "soft studio light with gentle ambient occlusion, no background shadow",
      color: "bright modern palette, glossy or soft-clay finish",
      mood: "playful, premium, modern UI",
      detail: "smooth rounded geometry, clean physically-based materials, crisp edges, no halos or fringing",
    },
    avoid: ["background", "cast shadow on a surface", "gritty realism", "green spill", "halos or fringing", "text", "watermark"],
  },
  {
    id: "glyph-icon",
    category: "webdev",
    title: "UI glyph icon (transparent)",
    description: "A clean single-weight line/glyph icon for UI. Monochrome, transparent, scalable.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a clean UI glyph icon in a single-weight line style",
      composition: "one simple centered pictogram with generous even padding, aligned to a tidy grid",
      color: "monochrome single solid color, no fill",
      mood: "minimal, modern, functional",
      detail: "consistent stroke weight, rounded line caps, crisp scalable vector-like edges, instantly readable at small sizes",
    },
    avoid: ["photorealism", "gradients", "drop shadows", "fill", "fine detail", "text", "watermark"],
  },
  {
    id: "spot-illustration",
    category: "webdev",
    title: "Spot illustration (transparent)",
    description: "Modern feature / empty-state illustration for web & apps. Transparent.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a modern flat spot illustration for a web feature or empty state",
      composition: "a clear friendly conceptual scene or object, balanced with generous negative space, isolated",
      color: "cohesive limited palette with soft tasteful gradients and one clear accent color",
      mood: "friendly, modern, product-marketing",
      detail: "clean shapes, subtle gradients and soft depth, polished tech-illustration style, crisp edges",
    },
    avoid: ["photorealism", "harsh outlines", "clip-art look", "busy clutter", "background", "watermark"],
  },
  {
    id: "abstract-blob",
    category: "webdev",
    title: "Decorative blob (transparent)",
    description: "A soft organic gradient blob/shape for section backgrounds and accents. Transparent.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a decorative abstract background shape",
      composition: "a single soft organic blob or fluid gradient shape, centered, isolated",
      color: "smooth modern gradient (brand-friendly), soft and tasteful",
      mood: "calm, contemporary, decorative",
      detail: "smooth clean vector-like shape with soft edges, optional very subtle grain, no hard outline",
    },
    avoid: ["hard outline", "busy detail", "photorealism", "background", "text", "watermark"],
  },
  {
    id: "mesh-gradient",
    category: "webdev",
    title: "Mesh / aurora gradient background",
    description: "Full-bleed modern mesh-gradient hero background (opaque). For landing sections.",
    recommended: { size: "1536x1024", quality: "high", format: "png" },
    dims: {
      medium: "a modern full-bleed mesh / aurora gradient background",
      composition: "a smooth multi-color mesh gradient filling the whole frame, no subject, with a calm area suitable for overlaid text",
      color: "soft blended contemporary hues (violet, blue, teal, pink) with smooth transitions",
      mood: "premium, calm, contemporary",
      detail: "smooth seamless gradient blend with subtle fine grain to prevent banding",
    },
    avoid: ["visible banding", "harsh edges", "any subject or object", "text", "watermark"],
  },
  {
    id: "device-mockup",
    category: "webdev",
    title: "Device mockup (transparent)",
    description: "A floating phone/laptop showing an app screen, isolated. For showcasing UIs.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a clean device mockup showing an app",
      composition: "a single modern smartphone at a slight three-quarter angle displaying a polished app screen, floating and isolated",
      lighting: "soft studio light with a subtle screen glow, no background shadow",
      color: "neutral device body, vibrant realistic app UI on the screen",
      mood: "premium, product-showcase, modern",
      detail: "crisp device edges, realistic on-screen UI with clean layout, fully isolated, no halos or fringing",
    },
    avoid: ["background scenery", "cast ground shadow", "gibberish on-screen text", "green spill", "halos or fringing", "watermark"],
  },
  {
    id: "avatar",
    category: "webdev",
    title: "Avatar illustration (transparent)",
    description: "A stylized profile avatar for users/testimonials. Transparent, consistent style.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a stylized character avatar illustration",
      composition: "a friendly head-and-shoulders avatar, centered, simple and clear, isolated",
      color: "modern flat palette with soft shading and one accent",
      mood: "friendly, approachable, contemporary",
      detail: "clean vector-like style, rounded shapes, distinctive and consistent, crisp edges",
    },
    avoid: ["photorealism", "busy background", "harsh outlines", "background", "halos or fringing", "watermark"],
  },
  {
    id: "mascot",
    category: "webdev",
    title: "Brand mascot (transparent)",
    description: "A single friendly brand mascot character for a product/site. Transparent.",
    recommended: { size: "1024x1024", quality: "high", format: "png" },
    background: "transparent",
    dims: {
      medium: "a friendly brand mascot character",
      composition: "a single full-body mascot in a clear, lively but readable pose, centered and isolated",
      color: "bold cohesive brand palette, simple clean shading",
      mood: "friendly, memorable, brandable",
      detail: "clean modern character design, expressive face, consistent proportions, crisp edges, no halos or fringing",
    },
    avoid: ["background scenery", "photorealism", "inconsistent design", "green spill", "halos or fringing", "watermark"],
  },
  {
    id: "wireframe",
    category: "webdev",
    title: "Lo-fi UI wireframe",
    description: "A greyscale low-fidelity wireframe of an app/web screen. For planning & specs.",
    recommended: { size: "1024x1536", quality: "high", format: "png" },
    dims: {
      medium: "a low-fidelity UI wireframe mockup",
      composition: "a clean greyscale wireframe of an app or web screen with clear layout blocks, header, content cards, and a nav, neatly aligned on a grid",
      color: "greyscale only: light-grey boxes and placeholders, mid-grey lines on a white background",
      mood: "schematic, structural, planning-stage",
      detail: "simple grey boxes, placeholder lines for text, basic outline icons, neat alignment, no real content or color",
    },
    avoid: ["full color", "realistic finished UI", "photorealism", "real legible body text", "watermark"],
  },
];
